import type { GuidePageProps } from "@/components/GuidePage";

const ucatFormat = { label: "UCAT: test format and scoring", href: "https://www.ucat.ac.uk/about-ucat/test-format-and-scoring/" };
const ucatPractice = { label: "UCAT: official practice tests", href: "https://www.ucat.ac.uk/prepare/practice-tests/" };
const entryRequirements = { label: "Medical Schools Council: entry requirements", href: "https://www.medschools.ac.uk/for-students/applying-to-medical-school/entry-requirements/" };
const experience = { label: "Medical Schools Council: work experience", href: "https://www.medschools.ac.uk/for-students/applying-to-medical-school/work-experience/" };
const personalStatement = { label: "UCAS: personal statements from 2026 entry", href: "https://www.ucas.com/applying/applying-to-university/writing-your-personal-statement/how-to-write-your-personal-statement-for-2026-entry-onwards" };

export const admissionsGuides: Record<string, GuidePageProps> = {
  "personal-statements-guide": {
    eyebrow: "Your application", title: "A personal statement that sounds like you.",
    intro: "Build a clear, reflective application for medicine or dentistry. Start with your own evidence, organise it around the current UCAS questions, and explain what each experience taught you.",
    takeaway: "You do not need a dramatic opening. You need specific experiences, thoughtful reflection and a clear reason for choosing the course.",
    sections: [
      { title: "Understand the current format", paragraphs: ["For 2026 entry onwards, UCAS uses three responses: your motivation for the course, preparation through education, and preparation outside education. The total limit is 4,000 characters including spaces, with at least 350 characters in each answer.", "You can divide the remaining space to suit your evidence. Treat the three answers as one coherent application: avoid repeating the same example in every section."], action: "Make three headings in a document and place each experience under the heading it supports best." },
      { title: "Explain your motivation", paragraphs: ["Describe what draws you to the work of a doctor or dentist, and what you have done to explore that interest. A conversation, volunteering experience or piece of independent reading is useful when you explain how it changed your understanding.", "Be specific about the profession you are applying for. Consider its responsibilities, uncertainty, teamwork and demands as well as the parts you find rewarding. Avoid claims that one placement proved you already understand the whole career."], example: { title: "A useful drafting prompt", text: "What did I initially believe about this profession? What did I observe or investigate? What became clearer, and what do I still want to understand?" } },
      { title: "Connect study to the course", paragraphs: ["Choose an example from your learning that shows how you think. Explain a concept you found interesting, the question it raised, or the approach you used to work through a difficult problem.", "An essay, practical, project or independent investigation can show preparation. Explain your contribution and learning rather than listing subjects or repeating grades that appear elsewhere in your application."], action: "Pick one academic example and write two sentences explaining your reasoning, not just the topic." },
      { title: "Turn experience into reflection", paragraphs: ["Use a short sequence: what happened, what you noticed, what you learned, and how you used that learning. Work, caring responsibilities, volunteering and interests can all provide evidence when the link is thoughtful.", "Distinguish your role from the professional's role. Describe observation as observation. Keep patient details anonymous and include only experiences you can honestly discuss at interview."], example: { title: "Illustrative example - write your own", text: "During a community activity, I noticed that repeating instructions did not resolve confusion. Breaking the task into steps and checking understanding helped. It made me more aware that effective communication means adapting to the person, rather than simply providing more information." } },
      { title: "Edit for clarity and honesty", points: ["Replace broad adjectives such as 'caring' with an example that supports the quality.", "Remove repeated ideas and sentences that could belong to any applicant.", "Keep your own voice. Feedback should clarify your writing without inventing experiences or replacing your authorship.", "Read the answers aloud and check the character count in the UCAS application itself.", "Check how each chosen course uses personal statements; selection policies differ."], action: "Ask a reader to underline the learning in every example. If they cannot find it, revise that passage." },
    ],
    checklist: ["Each response answers its own question.", "Every example includes a clear learning point.", "No patient identifiers or exaggerated responsibilities remain.", "The three answers meet the individual minimums and overall character limit."],
    sources: [personalStatement], ctaLabel: "Get personal statement feedback", ctaHref: "/personal-statement-session",
    related: [{ label: "Work experience", href: "/work-experience-guide", description: "Gather evidence worth reflecting on." }, { label: "Year 12 planning", href: "/year12-guide", description: "Bring your preparation together." }, { label: "Interview preparation", href: "/interviews", description: "Practise explaining your experiences." }],
  },
  "work-experience-guide": {
    eyebrow: "Explore the profession", title: "Make your work experience count.",
    intro: "Learn what to notice, how to reflect, and how to discuss an experience without turning it into a list of hours. Useful learning can come from care, service, employment and observation.",
    takeaway: "The value of an experience lies in what you understand afterwards. Record small, specific moments while they are still fresh.",
    sections: [
      { title: "Start with a question", paragraphs: ["Before an activity, choose something you want to understand: how a team communicates, how someone explains uncertainty, or how a professional balances several demands. A question gives your observation a purpose.", "Use the experience to explore whether the profession suits you. Notice routine work, practical constraints and difficult moments as well as memorable consultations."], action: "Write two questions before your next activity, then revisit them afterwards." },
      { title: "Find accessible opportunities", paragraphs: ["Hospital shadowing is one option, but caring and service activities can also develop insight. Consider community volunteering, care settings, paid work with people, conversations with professionals and virtual experience.", "The Medical Schools Council describes several ways to gain relevant experience. Check each course's requirements, and follow the placement provider's age limits, safeguarding and supervision arrangements."], points: ["Choose something you can attend reliably and contribute to appropriately.", "Ask a clear, polite question when contacting an organisation; explain your availability and interests.", "If one route is unavailable, explore other ways to learn rather than waiting indefinitely for a hospital placement."] },
      { title: "Notice people, not just procedures", points: ["Communication: how did someone check understanding or adapt their language?", "Teamwork: what did different members contribute, and how did they share information?", "Dignity: how were privacy, preferences and comfort respected?", "Uncertainty: what happened when an answer was not immediately available?", "Responsibility: what were you allowed to do, and when did you need supervision?"], action: "Choose one moment and describe the behaviour that made it effective." },
      { title: "Keep a useful reflection diary", paragraphs: ["Use four short headings: situation, observation, learning, next action. Record your own contribution separately from what you watched someone else do.", "Do not keep names, dates of birth, photographs or other identifying patient information. A meaningful reflection does not need a detailed clinical story."], example: { title: "Reflection template", text: "Situation: someone was anxious about a task. Observation: the team member listened before explaining. Learning: finding the concern changed the explanation needed. Next action: I will ask what someone is unsure about before offering advice." } },
      { title: "Discuss it at interview", paragraphs: ["Use an experience that answers the question actually asked. Give brief context, explain your role, and spend most of the answer on learning and reflection. A STARR structure can help organise a genuine personal example without turning it into a memorised script.", "Prepare several examples so one anecdote does not have to answer every question. Be ready to discuss what did not go well, what you would change, and the limits of what you observed."], action: "Practise a 90-second reflection, then answer a follow-up asking what you would do differently." },
    ],
    checklist: ["Choose a realistic opportunity and a learning question.", "Keep anonymous notes soon after the activity.", "Prepare examples of communication, teamwork and a difficulty.", "Check your chosen courses' experience requirements."], sources: [experience, { label: "MSC and RCGP: reflective diary", href: "https://www.medschools.ac.uk/latest/publications/work-experience-reflective-diary/" }],
    ctaLabel: "Practise interview reflections", ctaHref: "/interviews",
    related: [{ label: "Personal statements", href: "/personal-statements-guide", description: "Turn evidence into clear writing." }, { label: "Year 12 planning", href: "/year12-guide", description: "Make time for experience and study." }, { label: "Healthcare careers", href: "/related-careers-guide", description: "Explore the wider team." }],
  },
  "year12-guide": {
    eyebrow: "Plan your next steps", title: "Your Year 12 application roadmap.",
    intro: "Balance schoolwork, career exploration and admissions preparation with a plan you can actually follow. Build the foundations early so your summer is manageable.",
    takeaway: "Start with your school timetable and academic priorities. Fit admissions preparation around them, then review the plan each half term.",
    sections: [
      { title: "Autumn: build your foundations", paragraphs: ["Settle into your subjects and find out how your school determines predicted grades. Use topic tests and teacher feedback to identify gaps before they grow.", "Begin a simple application folder for course research, reflections and useful questions. You do not need a finished personal statement or intensive UCAT timetable at this stage."], action: "Ask your teachers which assessments affect predictions and what improvement they need to see." },
      { title: "Spring: explore and reflect", points: ["Arrange a sustainable volunteering or service activity where possible.", "Explore medicine and dentistry through professional conversations, reading and experience.", "Compare subject requirements, selection policies and contextual eligibility on official course pages.", "Keep brief reflections that capture what changed your understanding.", "Review weak academic topics each week rather than leaving them for end-of-year exams."], action: "Create a course comparison sheet with a link to the current admissions policy for each option." },
      { title: "Summer: prepare deliberately", paragraphs: ["Build a UCAT plan backwards from your booked test date, taking holidays, work and rest into account. Start with the official tutorials so your materials match the current test.", "Draft the three personal statement responses from evidence you already have. A rough first draft is more useful than waiting for a perfect opening line."], example: { title: "An adaptable weekly rhythm", text: "Reserve separate blocks for academic gaps, UCAT practice and review, and one short application planning session. Reduce the load around school exams or other commitments instead of trying to maintain the same routine every week." } },
      { title: "Early Year 13: make informed choices", paragraphs: ["Once you have your test result and predictions, revisit course eligibility and selection policies. Check the UCAS deadline for your entry year and your school's earlier internal deadline.", "Leave time for your reference, application checks and any required supporting information. Ask for advice where a policy is unclear rather than assuming an exception applies."], action: "Add both the UCAS deadline and your school's internal deadline to your calendar." },
      { title: "Review your plan without panic", points: ["Choose two or three priorities for the coming week, not a list of everything left to do.", "If predicted grades are below a course's requirements, discuss academic support and realistic pathways.", "Keep rest and other interests in the timetable.", "Compare your progress with your own earlier work; another student's timetable may not fit you."], action: "At the end of the week, keep what worked and adjust one thing that did not." },
    ],
    checklist: ["Understand how your predicted grades are set.", "Keep a course requirements sheet with source links.", "Use one place for experience reflections.", "Plan UCAT practice and application deadlines around school commitments."], sources: [entryRequirements, { label: "UCAS: application dates and deadlines", href: "https://www.ucas.com/applying/applying-to-university/dates-and-deadlines-for-uni-applications" }],
    ctaLabel: "Explore A-Level support", ctaHref: "/alevel-tutoring",
    related: [{ label: "UCAT preparation", href: "/ucat-timeline", description: "Build a flexible practice plan." }, { label: "Work experience", href: "/work-experience-guide", description: "Learn from the opportunities you have." }, { label: "Personal statements", href: "/personal-statements-guide", description: "Organise your application evidence." }],
  },
  "gcse-revision-guide": {
    eyebrow: "Study with purpose", title: "A GCSE revision plan that earns its time.",
    intro: "Replace endless rereading with focused recall, exam questions and careful corrections. Use your specification and recent work to decide what deserves attention next.",
    takeaway: "Every revision session should leave you with something you can do better. Measure what you can recall or answer, not how polished your notes look.",
    sections: [
      { title: "Make a topic map", paragraphs: ["Find the specification for your exam board and qualification. Break it into manageable topics and rate each one using a recent question or a short closed-book explanation.", "Use three categories: secure, needs practice, and needs teaching. A topic feels familiar when you reread it, but that does not prove you can answer a question on it."], action: "Select one topic from each category and test whether your rating is accurate." },
      { title: "Use a repeatable study loop", points: ["Recall: explain or answer a question without looking at notes.", "Check: compare your answer with the source or mark scheme.", "Repair: identify the exact missing idea, step or phrase.", "Apply: answer a different question on the same idea.", "Return: revisit the topic after a gap to check it has stuck."], example: { title: "A focused 30-minute session", text: "Spend five minutes recalling a topic, fifteen on questions, and ten marking and correcting. Write one specific target for your next session." } },
      { title: "Learn from the mark scheme", paragraphs: ["Match each mark to the part of your answer that earned it. Notice command words, units, working and the level of explanation expected.", "Keep an error log with a short description of the mistake and the correction. Categorise errors as knowledge, application, calculation or timing so your next task targets the actual problem."], action: "Rewrite one incomplete explanation, then try another question without the mark scheme." },
      { title: "Practise timing gradually", paragraphs: ["Move from topic questions to timed sections, then full papers when you have enough coverage. Use the conditions and permitted equipment for your qualification.", "A low paper score should lead to a useful diagnosis. Separate unanswered questions from incorrect attempts; these often need different solutions."], action: "After a timed section, choose one timing adjustment and one content gap to work on." },
      { title: "Keep the plan sustainable", points: ["Give weaker subjects regular attention without abandoning stronger ones.", "Schedule short, specific tasks rather than vague blocks labelled 'revise'.", "Ask a teacher for help when repeated practice does not resolve a misunderstanding.", "Use the current exam board timetable for dates and build in breaks.", "If you are considering medicine or dentistry, check course GCSE policies individually; requirements differ."], action: "Write tomorrow's first revision task before you finish today." },
    ],
    checklist: ["Use the correct specification and exam board.", "Test your knowledge before choosing a topic.", "Mark, correct and retry questions.", "Keep a realistic weekly plan and an error log."], sources: [entryRequirements], ctaLabel: "Explore GCSE tutoring", ctaHref: "/gcse-tutoring",
    related: [{ label: "Year 12 planning", href: "/year12-guide", description: "Prepare for the next stage." }, { label: "Healthcare careers", href: "/related-careers-guide", description: "Explore what interests you." }, { label: "Admissions resources", href: "/resources", description: "Find the right next resource." }],
  },
  "ucat-timeline": {
    eyebrow: "Prepare for the UCAT", title: "Build your UCAT plan backwards.",
    intro: "A flexible preparation timeline for learning the test, practising under time pressure and reviewing what went wrong. Adapt the suggested stages to your test date and available time.",
    takeaway: "More questions are only useful when they change your next attempt. Make time for review, targeted practice and rest alongside mocks.",
    sections: [
      { title: "Start with the current test", paragraphs: ["The UCAT has three cognitive subtests: Verbal Reasoning, Decision Making and Quantitative Reasoning. Situational Judgement is reported separately. Abstract Reasoning is no longer part of the test.", "Use the current official tutorials, timings and practice materials. Choose your test date around commitments and available appointments, and check current booking and access arrangement rules directly with UCAT."], action: "Open the official tutorials before buying or reusing a question bank." },
      { title: "Weeks 1-2: learn before rushing", paragraphs: ["Begin untimed to understand question types, instructions and the test interface. Learn a method, use it on a small set, and explain your mistakes.", "Try the calculator, keyboard shortcuts and flagging controls in the official practice environment. Build familiarity before judging yourself on speed."], points: ["Verbal Reasoning: find evidence for the answer rather than relying on outside knowledge.", "Decision Making: choose a clear way to represent the information and check the logic.", "Quantitative Reasoning: identify the required calculation, units and useful data.", "Situational Judgement: explain the professional principle behind your answer."] },
      { title: "Weeks 3-5: make timing specific", paragraphs: ["Introduce timed sets for one question type at a time. Record whether errors came from knowledge, method, interpretation or time pressure. There is no universal accuracy percentage you must reach before progressing.", "Practise moving on from a question that is consuming too much time. Review it afterwards to decide whether a better method would have helped or whether skipping was sensible."], example: { title: "A useful error-log entry", text: "QR: selected the wrong population before calculating a percentage. Fix: underline the denominator and check the units before using the calculator. Next task: a short set of percentage questions." }, action: "Repeat one troublesome question type with a single change to your method." },
      { title: "Final weeks: rehearse and review", paragraphs: ["Add full mocks to practise pacing, stamina and switching between subtests. Leave enough time to review each mock thoroughly before doing another.", "Track sections separately and compare similar practice conditions. Commercial scaled scores are estimates; use official guidance for the real score format. You do not need a full mock every day to make progress."], action: "Use your last mock to choose two targeted tasks before the next one." },
      { title: "Final days: keep it familiar", points: ["Check your appointment, accepted identification and test-day instructions.", "Use familiar methods and avoid rebuilding your strategy at the last minute.", "Keep short practice and review sessions if they help you feel ready.", "Protect sleep and leave time for travel or other practical arrangements.", "If considering a booking change, check the current deadlines and availability first."], action: "Write a brief test-day plan and check it against the official instructions." },
    ],
    checklist: ["Use resources for the current four-subtest format.", "Practise in the official interface.", "Keep a short, specific error log.", "Balance timed work, full mocks, review and rest."], sources: [ucatFormat, ucatPractice, { label: "UCAT: test dates", href: "https://www.ucat.ac.uk/about-ucat/ucat-test-dates/" }],
    ctaLabel: "Explore UCAT tutoring", ctaHref: "/ucat-tutoring",
    related: [{ label: "Free score tracker", href: "/ucat-score-tracker", description: "Keep a record of practice and review." }, { label: "Mock difficulty spreadsheet", href: "/ucat-mock-difficulty", description: "Add context to commercial mock scores." }, { label: "Year 12 planning", href: "/year12-guide", description: "Balance preparation with schoolwork." }],
  },
  "gateway-foundation-guide": {
    eyebrow: "Explore your options", title: "Understand gateway and foundation routes.",
    intro: "Compare the purpose, eligibility and progression rules of alternative routes into medicine or dentistry. A course title alone does not tell you whether a programme fits your circumstances.",
    takeaway: "Check the exact course code, entry year and progression conditions. A generic foundation course is not a guaranteed route into medicine or dentistry.",
    sections: [
      { title: "Know what the route leads to", paragraphs: ["Some programmes include an additional preparatory year as part of a longer medical degree. Others are separate courses with conditions for progression or further application.", "Read the official course page carefully. Confirm the qualification, institution, course code and what happens after the preparatory year rather than relying on the words 'foundation' or 'gateway'."], action: "Write down the qualification and progression conditions for each course you are considering." },
      { title: "Check eligibility first", points: ["Look at the programme's published widening participation or contextual criteria.", "Check domicile, fee status, school background and geographical restrictions where relevant.", "Check required subjects, predicted or achieved grades and resit policies.", "Check admissions test, interview and experience requirements.", "Find out what evidence or additional form is required, and when it must be submitted."], paragraphs: ["Criteria are programme-specific. Meeting one contextual indicator does not automatically make you eligible for every gateway course."] },
      { title: "Compare progression and cost", paragraphs: ["Ask what academic and professional requirements apply to progression. Establish whether progression is assured when conditions are met, competitive, or requires a new application.", "Check the total length of study, fees and funding for your circumstances. A longer route can affect living costs and planning as well as the academic timetable."], action: "Contact admissions with one precise question if the progression wording is unclear." },
      { title: "Make a realistic shortlist", paragraphs: ["Use the Medical Schools Council entry requirements tool as a starting point for medicine, then confirm the information on the university's own current course page. Research dentistry routes directly with their providers.", "Compare these routes with other options that fit your circumstances, such as standard entry, a planned resit or another healthcare profession. Choose a pathway for its actual conditions and outcome."], example: { title: "Course comparison headings", text: "Course and UCAS code / entry year / eligibility / academic requirements / test and interview / progression conditions / course length / funding / evidence deadline / official source." } },
    ],
    checklist: ["Verify eligibility for the exact programme.", "Understand how progression works.", "Check required evidence and deadlines.", "Confirm funding and the total course length."], sources: [entryRequirements, { label: "Medical Schools Council: making an application", href: "https://www.medschools.ac.uk/for-students/applying-to-medical-school/making-an-application/" }],
    ctaLabel: "Ask about your application options", ctaHref: "/contact",
    related: [{ label: "Healthcare careers", href: "/related-careers-guide", description: "Compare different professional roles." }, { label: "Year 12 planning", href: "/year12-guide", description: "Build a considered application plan." }, { label: "Personal statements", href: "/personal-statements-guide", description: "Explain your motivation clearly." }],
  },
  "related-careers-guide": {
    eyebrow: "Explore healthcare", title: "Find the healthcare role that fits you.",
    intro: "Look beyond a degree title. Compare the work people do, the way they train, and the responsibilities they hold before deciding what you want from a healthcare career.",
    takeaway: "Start with the kind of work you enjoy: direct care, investigation, rehabilitation, medicines or research. Then explore the professions that do it.",
    sections: [
      { title: "Start with your interests", points: ["Do you enjoy sustained relationships, brief consultations or work behind the scenes?", "Are you drawn to explaining, practical treatment, laboratory investigation or rehabilitation?", "What have you actually enjoyed in study, work or volunteering?", "Which parts of a role would you find difficult, and how could you learn more about them?"], action: "Choose two interests and one uncertainty to guide your research." },
      { title: "Explore the wider team", paragraphs: ["Start with NHS Health Careers to explore roles such as nursing, radiography, physiotherapy, pharmacy and healthcare science. Use its role profiles to learn what the work involves and how entry routes differ.", "Dental hygiene and dental therapy have their own qualifications and registration routes. Check the General Dental Council's approved provider information when researching those courses."], action: "Read two role profiles and note one difference in their day-to-day responsibilities." },
      { title: "Check the qualification carefully", paragraphs: ["Verify whether a programme meets the requirements for the profession you want to enter. Course accreditation, placements, registration and further training can matter as much as the course title.", "A related degree should be a course you would be willing to complete for its own merits. Do not assume it includes a transfer into medicine or dentistry; any transfer route needs explicit confirmation from the university."], example: { title: "Questions for a course provider", text: "Which professional qualification does this programme lead to? Is further training required? How are placements arranged? Where can I check accreditation or regulator approval?" } },
      { title: "Compare real working lives", paragraphs: ["Speak to professionals where possible and ask about a typical week, responsibilities, teamwork, pressures and career development. Find out how the role varies between settings.", "Keep a comparison sheet with the role, entry route, training, placement arrangements and the reasons it interests you. You can change your preference as you learn more."], action: "Choose one profession to investigate in more depth and plan a practical next step." },
    ],
    checklist: ["Compare at least two professional roles.", "Check training and registration requirements.", "Ask about daily work and practical demands.", "Choose courses you would value independently of any hoped-for transfer."],
    sources: [{ label: "NHS Health Careers: explore roles", href: "https://www.healthcareers.nhs.uk/explore-roles" }, { label: "GDC: dental hygiene and therapy programmes", href: "https://www.gdc-uk.org/education-cpd/dental-education/quality-assurance/approved-providers/dental-therapy-and-dental-hygiene" }],
    ctaLabel: "Talk through your options", ctaHref: "/contact",
    related: [{ label: "Work experience", href: "/work-experience-guide", description: "Explore careers through experience." }, { label: "Gateway routes", href: "/gateway-foundation-guide", description: "Understand different entry pathways." }, { label: "Personal statements", href: "/personal-statements-guide", description: "Explain your course choice." }],
  },
  "ucat-score-tracker": {
    eyebrow: "Free planning tool", title: "Turn your mock scores into a plan.",
    intro: "Download the MedWithRish UCAT score tracker and use your practice history to choose what to work on next. A score is a starting point for review, not a verdict on your application.",
    takeaway: "Keep one consistent record of scores, conditions and lessons. Your next practice task should come from the mistakes behind the numbers.",
    sections: [
      { title: "Download and keep your own copy", paragraphs: ["The Excel workbook is available free below. Save a copy before you start entering results so you can return to the same record throughout your preparation.", "Inspect the workbook's headings and example cells before editing formulas. Use it alongside the current UCAT format: VR, DM and QR, with SJT recorded separately. If a legacy field appears in a copy, leave it out of current totals."], action: "Save your copy with a clear filename and enter one recent practice result." },
      { title: "Record the practice conditions", points: ["Record the date, provider and specific mock or set.", "Keep section results separate so a total does not hide an uneven performance.", "Note whether the attempt was timed, repeated, interrupted or completed with access arrangements.", "Add a short note about errors and the next practice task.", "Avoid mixing raw marks, percentages and scaled scores in the same column."], example: { title: "A useful note", text: "DM mock: ran out of time on the final questions. Review: spent too long rewriting a logic puzzle. Next task: a short timed puzzle set with a clear move-on rule." } },
      { title: "Interpret progress carefully", paragraphs: ["Compare several attempts under similar conditions. One unusually high or low score may say more about a particular set or a difficult day than your overall progress.", "Treat any practice score conversion as an estimate. A third-party workbook cannot guarantee an official test score, percentile, university cutoff or interview invitation."], action: "Look at your last few comparable attempts and pick a recurring issue." },
      { title: "Choose the next task", paragraphs: ["For knowledge errors, revisit the method and explain it. For timing errors, practise a small set with a specific pacing target. For repeated misreading, identify exactly which instruction or detail you missed.", "Review the result of that intervention before adding more mocks. The tracker is most useful when it changes your next action."], action: "Write two targeted tasks next to your latest score and schedule them." },
    ],
    checklist: ["Save your own workbook copy.", "Record the mock and practice conditions.", "Check that units and current test sections are consistent.", "Turn each review into a specific next task."], sources: [ucatFormat],
    ctaLabel: "Download the free tracker (.xlsx)", ctaHref: "/downloads/MedWithRish_UCAT_Score_Tracker.xlsx", download: true,
    related: [{ label: "UCAT preparation timeline", href: "/ucat-timeline", description: "Give your practice a structure." }, { label: "Mock difficulty spreadsheet", href: "/ucat-mock-difficulty", description: "Understand the limits of comparisons." }, { label: "UCAT tutoring", href: "/ucat-tutoring", description: "Work on a specific sticking point." }],
  },
  "ucat-mock-difficulty": {
    eyebrow: "Community practice resource", title: "Put your UCAT mock scores in context.",
    intro: "Use the shared difficulty spreadsheet to compare practice experiences, then bring the focus back to your own errors, timing and progress.",
    takeaway: "Community averages can add context. They do not tell you what your official score will be or which mock every student should find easy.",
    sections: [
      { title: "Open the shared spreadsheet", paragraphs: ["The MedWithRish spreadsheet brings together student-reported practice scores and difficulty comparisons. Open the live sheet to see the available results rather than relying on an older screenshot.", "Different providers, mocks and participants can produce different averages. Use the data to ask better questions about your practice, not to predict a test-day result."], action: "Find a mock you have completed and compare the section pattern with your own review." },
      { title: "Read comparisons with care", points: ["Check the provider and exact mock before comparing scores.", "Look at how many responses support an average where that information is available.", "Remember that contributors may differ in preparation, conditions and whether they repeated a mock.", "Keep the current three-cognitive-subtest total separate from legacy formats.", "Use official UCAT materials to understand the test format and scoring."], example: { title: "A better question", text: "Instead of 'Is my score good enough?', ask 'Did this mock expose a repeated difficulty in QR, and which calculation or timing decision caused it?'" } },
      { title: "Contribute your scores", paragraphs: ["Use the score submission form if you want to contribute a completed practice result. Identify the provider and mock accurately and follow the form's instructions.", "Do not include patient information, passwords or unrelated personal details in a practice result. Use your own score tracker for a detailed record of preparation."], action: "Submit a result only when you can identify the exact practice test." },
    ],
    sources: [ucatFormat, ucatPractice], ctaLabel: "Open the live spreadsheet", ctaHref: "https://docs.google.com/spreadsheets/d/1_MhhGQyXX3o_qbL6-QFc1KZAj3XFXn2d-oiBvIuSFM4/edit?gid=9647191#gid=9647191",
    secondaryAction: { label: "Submit your scores", href: "https://docs.google.com/forms/d/e/1FAIpQLScvWGoTQcElu1U8R1O_EqMHlyRuZ3T7gzXYrXhBsWj3AUyZPw/viewform?usp=header" },
    related: [{ label: "UCAT tutoring", href: "/ucat-tutoring", description: "Work on a specific sticking point." }, { label: "Free score tracker", href: "/ucat-score-tracker", description: "Keep your own progress record." }, { label: "UCAT preparation", href: "/ucat-timeline", description: "Plan the next stage of practice." }],
  },
};
