"use client";

import { useState } from "react";
import { ArrowLeft, ArrowRight, AudioLines, Check, ChevronDown, Clock3, FileText, Loader2, Maximize2, MessageSquareText, Mic, MicOff, Minimize2, PhoneOff, Sparkles, Video, VideoOff, Volume2, VolumeX, X } from "lucide-react";
import type { InterviewAnswer, InterviewAttempt } from "../_lib/interview-types";
import type { useInterviewDevices } from "../_lib/useInterviewDevices";
import type { useInterviewSpeech } from "../_lib/useInterviewSpeech";
import { InterviewDevicePreview } from "./InterviewDevicePreview";
import styles from "./AIInterviewRoom.module.css";

export const formatRoomTime = (seconds: number) => `${Math.floor(Math.max(0, seconds) / 60)}:${String(Math.max(0, seconds) % 60).padStart(2, "0")}`;
type Props = {
  attempt: InterviewAttempt; answers: InterviewAnswer[]; questionIndex: number;
  preparing: boolean; expired: boolean; active: boolean; secondsRemaining: number;
  speech: ReturnType<typeof useInterviewSpeech>; devices: ReturnType<typeof useInterviewDevices>;
  saved: boolean; busy: string; preview: boolean; readAloud: boolean;
  microphoneConsent: boolean; setMicrophoneConsent: (enabled: boolean) => void;
  setReadAloud: (enabled: boolean) => void; onAnswer: (value: string) => void;
  onQuestion: (index: number) => void; onSubmit: () => void; onLeave: () => void;
  wordCount: number; onSkipPreparation: () => void;
};

export function AIInterviewCall(props: Props) {
  const [tab, setTab] = useState<"transcript" | "notes">("transcript");
  const [notes, setNotes] = useState("");
  const [focus, setFocus] = useState(false);
  const [endDialog, setEndDialog] = useState(false);
  const { attempt, speech, devices, questionIndex, answers, preparing, expired, active, busy, preview } = props;
  const question = attempt.questions[questionIndex];
  const status = busy ? "One moment…" : preparing ? "Take a moment to think" : expired ? "Time to reflect" : speech.speaking ? "Reading your question" : speech.listening ? "Listening to you" : "Ready when you are";

  return <div className={`${styles.callRoom} ${focus ? styles.focusRoom : ""}`}>
    <header className={styles.roomHeader}><div className={styles.roomBrand}><span className={styles.brandMark}><AudioLines size={20} /></span><div><strong>phloem <span>interview room</span></strong><p>{preview ? "Preview session" : "Private practice"} <span>·</span> Station {attempt.stationIndex + 1} of {attempt.stationCount}</p></div></div><div className={`${styles.roomTimer} ${!preparing && props.secondsRemaining < 60 ? styles.timerUrgent : ""}`} role="timer" aria-label={`${preparing ? "Preparation" : "Station"} time remaining`}><Clock3 size={16} /><span>{preparing ? "Reading time" : expired ? "Time complete" : "Station time"}</span><strong>{formatRoomTime(props.secondsRemaining)}</strong></div></header>
    <div className={styles.callLayout}>
      <div className={styles.stageColumn}>
        <div className={styles.interviewerStage}>
          <div className={styles.stageTop}><span className={styles.roomPill}><span className={styles.greenDot} /> {preparing ? "PREPARATION" : "PRACTICE IN PROGRESS"}</span><button type="button" className={styles.stageIcon} aria-label={focus ? "Exit focus view" : "Enter focus view"} aria-pressed={focus} onClick={() => setFocus(!focus)}>{focus ? <Minimize2 size={17} /> : <Maximize2 size={17} />}</button></div>
          <div className={styles.interviewerIdentity}><div className={`${styles.interviewerOrb} ${speech.speaking ? styles.orbSpeaking : ""}`}><span /><span /><div><AudioLines size={45} strokeWidth={1.25} /></div></div><h2>Your Phloem interviewer</h2><p><span className={speech.listening ? styles.listeningDot : styles.greenDot} />{status}</p><span className={styles.avatarNote}>AI voice · illustrative avatar</span></div>
          <div className={styles.questionCaption}><span>QUESTION {questionIndex + 1} / {attempt.questions.length}</span><p>{question}</p><button type="button" onClick={() => speech.speaking ? speech.stopSpeaking() : void speech.speak(question)} disabled={!speech.voiceSupported || Boolean(busy)}>{speech.speaking ? <VolumeX size={14} /> : <Volume2 size={14} />}{speech.speaking ? "Stop reading" : "Hear question again"}</button></div>
          <div className={styles.stageBottom}><span><Sparkles size={13} /> A conversation. One answer at a time.</span><span>{attempt.title}</span></div>
        </div>
        <div className={styles.belowStage}><div className={styles.stationContext}><span className={styles.eyebrow}>{preparing ? "BEFORE YOU BEGIN" : "A LITTLE REMINDER"}</span><h3>{preparing ? "Read. Breathe. Gather your thoughts." : "You don’t need a perfect answer."}</h3><p>{preparing ? "Answering opens after reading time. The timer continues if you leave this tab." : "Think out loud, use a real example, and tell us what you learned. You can correct the transcript before submitting."}</p>{preparing && preview && <button type="button" className={styles.textButton} onClick={props.onSkipPreparation}>Skip reading time in preview <ArrowRight size={14} /></button>}</div><InterviewDevicePreview stream={devices.stream} compact /></div>
      </div>
      <aside className={styles.transcriptPanel} aria-label="Interview transcript and notes">
        <div className={styles.transcriptTabs}><button type="button" aria-pressed={tab === "transcript"} onClick={() => setTab("transcript")}><MessageSquareText size={16} />Transcript</button><button type="button" aria-pressed={tab === "notes"} onClick={() => setTab("notes")}><FileText size={16} />Notes</button></div>
        {tab === "transcript" ? <><div className={styles.transcriptIntro}><span><span className={speech.listening ? styles.listeningDot : styles.greenDot} /> {speech.listening ? "Live transcription" : "Your conversation"}</span><span>Q{questionIndex + 1} of {attempt.questions.length}</span></div><div className={styles.transcriptScroll}>{answers.slice(0, questionIndex).map((answer, index) => <details className={styles.previousAnswer} key={answer.question}><summary>Question {index + 1}<ChevronDown size={13} /></summary><strong>{answer.question}</strong><p>{answer.answer || "No answer added."}</p></details>)}<div className={styles.speakerLabel}><span className={styles.miniInterviewer}><AudioLines size={13} /></span><strong>Phloem</strong><span>Interviewer</span></div><p className={styles.questionBubble}>{question}</p><div className={styles.speakerLabel}><span className={styles.miniYou}>Y</span><strong>You</strong><span>{speech.listening ? "Speaking" : "Candidate"}</span></div><label className={styles.answerLabel} htmlFor="interview-answer">{speech.listening ? "Your words appear here" : "Speak or type your answer"}</label><textarea id="interview-answer" value={answers[questionIndex]?.answer ?? ""} readOnly={!active || speech.listening} maxLength={6000} onChange={(event) => props.onAnswer(event.target.value)} placeholder={preparing ? "Your answer opens after reading time…" : "Start with what comes naturally…"} className={styles.answerInput} />{speech.interimTranscript && <p className={styles.interimText} aria-live="polite">{speech.interimTranscript}</p>}<p className={styles.characterCount}>{answers[questionIndex]?.answer.length ?? 0} / 6,000 · {speech.listening ? "Stop mic to edit" : "Editable transcript"}</p></div><div className={styles.transcriptFooter}><span><Check size={13} />{preview ? "Preview · nothing saved to your account" : props.saved ? "Saved to your account" : "Autosaves every 15 seconds"}</span><p>Questions spoken aloud and your answers, in one place.</p></div></> : <div className={styles.notesPanel}><h3>A little thinking space</h3><p>Jot down a structure or a few words to come back to.</p><label htmlFor="interview-notes" className={styles.answerLabel}>Your private scratchpad</label><textarea id="interview-notes" value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={5000} placeholder="Situation → action → what I learned…" /><p>Notes stay on this screen and aren’t saved, submitted or marked.</p></div>}
      </aside>
    </div>
    {(speech.error || devices.cameraError) && <p role="status" className={styles.callNotice}>{speech.error || devices.cameraError}</p>}
    {!speech.supported && <p className={styles.callNotice}>Speech recognition is unavailable in this browser. Type your answer in the transcript to continue.</p>}
    {speech.supported && !props.microphoneConsent && <label className={styles.callConsent}><input type="checkbox" checked={false} onChange={(event) => props.setMicrophoneConsent(event.target.checked)} /><span>Enable spoken answers. Your browser’s speech service may process audio; Phloem saves only your transcript.</span></label>}
    <footer className={styles.callControls}><div className={styles.deviceControls}><button type="button" disabled={!active || !props.microphoneConsent || !speech.supported} aria-pressed={speech.listening} className={speech.listening ? styles.controlActive : ""} onClick={() => speech.listening ? void speech.stop() : speech.start()}>{speech.listening ? <Mic size={20} /> : <MicOff size={20} />}<span>{speech.listening ? "Stop mic" : "Start mic"}</span></button><button type="button" aria-pressed={devices.cameraEnabled} disabled={devices.cameraPending || Boolean(busy)} onClick={() => void devices.toggleCamera()}>{devices.cameraEnabled ? <Video size={20} /> : <VideoOff size={20} />}<span>Camera {devices.cameraEnabled ? "on" : "off"}</span></button><button type="button" aria-pressed={props.readAloud} disabled={!speech.voiceSupported} onClick={() => props.setReadAloud(!props.readAloud)}>{props.readAloud ? <Volume2 size={20} /> : <VolumeX size={20} />}<span>Voice {props.readAloud ? "on" : "off"}</span></button></div><div className={styles.questionControls}><button type="button" aria-label="Previous question" disabled={!active || questionIndex === 0} onClick={() => props.onQuestion(questionIndex - 1)}><ArrowLeft size={17} /></button><div className={styles.questionDots} aria-label={`Question ${questionIndex + 1} of ${attempt.questions.length}`}>{attempt.questions.map((_, index) => <span key={index} data-active={questionIndex === index} />)}</div><button type="button" disabled={!active || questionIndex === attempt.questions.length - 1} onClick={() => props.onQuestion(questionIndex + 1)}>Next <ArrowRight size={15} /></button></div><button type="button" className={styles.endCallButton} disabled={Boolean(busy)} onClick={() => setEndDialog(true)}><PhoneOff size={18} /><span>Finish station</span></button></footer>
    {endDialog && <div className={styles.dialogBackdrop}><div role="dialog" aria-modal="true" aria-labelledby="finish-title" className={styles.finishDialog} onKeyDown={(event) => { if (event.key === "Escape" && !busy) setEndDialog(false); if (event.key === "Tab") { const items = event.currentTarget.querySelectorAll<HTMLButtonElement>('button:not(:disabled)'); const first = items[0]; const last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }}><button type="button" autoFocus aria-label="Return to interview" className={styles.closeDialog} disabled={Boolean(busy)} onClick={() => setEndDialog(false)}><X size={19} /></button><span className={styles.sectionIcon}><Check size={22} /></span><h2 id="finish-title">Ready to reflect?</h2><p>{preview ? "Explore a sample marking screen to see how your feedback will look. The example score is illustrative." : "Finish this station and turn your answers into a useful next step. Your transcript will be locked for marking."}</p><div className={styles.finishSummary}><span>{answers.filter((item) => item.answer.trim()).length} / {answers.length} prompts answered</span><span>{props.wordCount} words</span></div>{!preview && props.wordCount < 20 && <p className={styles.deviceError}>Add at least 20 words across your answers to receive feedback.</p>}<button type="button" className={styles.primaryButton} disabled={Boolean(busy) || (!preview && (preparing || props.wordCount < 20))} onClick={() => { setEndDialog(false); props.onSubmit(); }}>{busy ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}{preview ? "See sample feedback" : "Finish & get feedback"}</button><button type="button" className={styles.secondaryButton} disabled={Boolean(busy)} onClick={() => setEndDialog(false)}>Keep practising</button><button type="button" className={styles.leaveButton} disabled={Boolean(busy)} onClick={props.onLeave}>{preview ? "Leave preview" : "End without feedback (uses this attempt)"}</button></div></div>}
  </div>;
}
