"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, AudioLines, Check, CheckCircle2, Clock3, Download, FileText, LockKeyhole, RotateCcw, Sparkles, Target, TrendingUp } from "lucide-react";
import type { InterviewAttempt } from "../_lib/interview-types";
import { formatRoomTime } from "./AIInterviewCall";
import styles from "./AIInterviewRoom.module.css";

export function AIInterviewFeedback({ attempt, preview = false, onRetry, onNext, nextLabel, breakRemaining = 0, busy = false }: { attempt: InterviewAttempt; preview?: boolean; onRetry: () => void; onNext?: () => void; nextLabel?: string; breakRemaining?: number; busy?: boolean }) {
  const [tab, setTab] = useState<"overview" | "criteria" | "transcript">("overview");
  const feedback = attempt.feedback;
  if (!feedback) return null;
  const download = () => {
    const text = `${preview ? "PREVIEW — illustrative feedback, not a real assessment\n\n" : ""}${attempt.title}\nPractice score: ${feedback.score}%\n\n${feedback.summary}\n\nWHAT WORKED WELL\n${feedback.strengths.join("\n")}\n\nNEXT STEPS\n${feedback.improvements.join("\n")}\n\nTRANSCRIPT\n${attempt.answers.map((answer) => `Q: ${answer.question}\nA: ${answer.answer || "No answer added."}`).join("\n\n")}`;
    const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = `phloem-${preview ? "sample-" : ""}interview-feedback.txt`; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div className={styles.feedbackPage}>
    <div className={styles.setupHeading}><div><p className={styles.eyebrow}><CheckCircle2 size={15} /> {preview ? "SAMPLE FEEDBACK" : "STATION COMPLETE"}</p><h1>A little reflection. A stronger next attempt.</h1><p>{attempt.title} <span>·</span> Station {attempt.stationIndex + 1} of {attempt.stationCount}</p></div><button type="button" className={styles.secondaryButton} onClick={download}><Download size={16} /> Download feedback</button></div>
    {preview && <div role="note" className={styles.previewBanner}><Sparkles size={17} /><span><strong>This is a sample report.</strong> The score and comments are placeholders to show the experience, not an assessment of your answers.</span></div>}
    <section className={styles.scoreCard}><div className={styles.scoreRing} style={{ background: `conic-gradient(#b9f4db ${feedback.score}%, #35645b 0)` }}><div><strong>{feedback.score}<span>%</span></strong><span>{preview ? "Example score" : "Practice score"}</span></div></div><div><span className={styles.roomPill}><Sparkles size={13} /> YOUR FEEDBACK</span><h2>{preview ? "Here’s what useful feedback can look like." : "Every attempt gives you something to build on."}</h2><p>{feedback.summary}</p><span className={styles.scoreNote}>Practice guidance, not an admissions prediction. Overall scores are calibrated and capped at 99%.</span></div></section>
    <div className={styles.feedbackTabs} aria-label="Feedback view">{([['overview', 'Your takeaways'], ['criteria', 'Marking breakdown'], ['transcript', 'Your transcript']] as const).map(([value, label]) => <button type="button" key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}</button>)}</div>
    {tab === "overview" && <><div className={styles.feedbackGrid}><section className={styles.setupCard}><div className={styles.cardHeading}><span className={styles.sectionIcon}><CheckCircle2 size={20} /></span><div><h2>Keep doing this</h2><p>What worked well in your answer.</p></div></div><ul className={styles.feedbackList}>{feedback.strengths.map((item, index) => <li key={index}><Check size={16} /><span>{item}</span></li>)}</ul></section><section className={styles.setupCard}><div className={styles.cardHeading}><span className={styles.sectionIcon}><Target size={20} /></span><div><h2>Make your next answer stronger</h2><p>A few practical things to work on.</p></div></div><ol className={styles.feedbackList}>{feedback.improvements.map((item, index) => <li key={index}><span className={styles.stepNumber}>{index + 1}</span><span>{item}</span></li>)}</ol></section></div><div className={styles.nextStepCard}><span className={styles.sectionIcon}><TrendingUp size={21} /></span><div><span className={styles.eyebrow}>YOUR NEXT SMALL STEP</span><h3>{feedback.improvements[0] || "Choose one example and practise explaining what you learned."}</h3><p>Try it out loud once, then bring it into your next station.</p></div></div></>}
    {tab === "criteria" && <section className={styles.setupCard}><h2 className={styles.breakdownHeading}>How your answer was assessed</h2><p className={styles.smallNote}>Each criterion is scored out of 100. The calibrated overall score is not a simple average.</p><div className={styles.rubricList}>{feedback.rubric.map((criterion) => <div key={criterion.criterion}><div className={styles.rowBetween}><h3>{criterion.criterion}</h3><strong>{criterion.score}<span> / 100</span></strong></div><div className={styles.rubricTrack}><span style={{ width: `${Math.max(0, Math.min(100, criterion.score))}%` }} /></div><p>{criterion.reason}</p></div>)}</div><p className={styles.smallNote}>Feedback assesses your answer content. Accent, eye contact, camera use and movement are not scored.</p></section>}
    {tab === "transcript" && <section className={styles.setupCard}><div className={styles.cardHeading}><span className={styles.sectionIcon}><FileText size={20} /></span><div><h2>Your conversation, in your words</h2><p>{preview ? "Your preview answers appear below." : "The submitted transcript used for this feedback."}</p></div></div><div className={styles.reportTranscript}>{attempt.answers.map((answer, index) => <details key={answer.question} open={index === 0}><summary>Question {index + 1} <span>{answer.question}</span></summary><p>{answer.answer || "No answer added."}</p></details>)}</div></section>}
    <div className={styles.comingSoonGrid}>{[{ icon: AudioLines, title: "Answer replay", text: "Revisit key moments in your delivery." }, { icon: TrendingUp, title: "Compare attempts", text: "See how this answer develops over time." }].map((item) => <div key={item.title}><item.icon size={21} /><div><h3>{item.title} <span>Coming soon</span></h3><p>{item.text}</p></div><LockKeyhole size={14} /></div>)}</div>
    <div className={styles.joinBar}><div><strong>{onNext ? "Take a breath. Your next station is ready when you are." : "You showed up. That’s how confidence grows."}</strong><p>{breakRemaining > 0 ? <><Clock3 size={14} /> Break · {formatRoomTime(breakRemaining)} remaining</> : "Choose one improvement to carry into your next conversation."}</p></div><div className={styles.joinActions}><button type="button" className={styles.secondaryButton} disabled={busy} onClick={onRetry}><RotateCcw size={15} /> Back to setup</button>{onNext && <button type="button" className={styles.primaryButton} disabled={busy || breakRemaining > 0} onClick={onNext}>{nextLabel || "Next station"}<ArrowRight size={16} /></button>}{!preview && <Link className={styles.textButton} href={`/phloemai/interviews/reports/${attempt.id}`}>Saved report <ArrowUpRight size={15} /></Link>}</div></div>
  </div>;
}
