import Link from "next/link";
import { ArrowRight, BookOpen } from "lucide-react";

const guides = [
  { title: "Build your Why medicine? answer", tag: "MOTIVATION", paragraphs: ["Start with your own reasons for wanting to become a doctor. Connect them to an experience you can describe honestly, then explain what you learnt and how it shaped your understanding of the role.", "Explore both the appeal and the challenges. Explain why medicine fits you while respecting other healthcare careers. A thoughtful answer sounds like your experience, rather than a script you have memorised."], station: "why-medicine" },
  { title: "Reflect on work experience", tag: "REFLECTION", paragraphs: ["Choose one moment: what happened, what you noticed, and why it mattered. Reflection is more useful than listing activities or clinical procedures.", "Describe what you would carry into future learning. Use anonymised examples and avoid identifying patients or sharing private details. Experiences in caring, volunteering or everyday teamwork can also offer useful reflection."], station: "work-experience" },
  { title: "Approach an ethical discussion", tag: "REASONING", paragraphs: ["Clarify the situation and acknowledge what you do not know. Identify who is affected, consider different perspectives, and explain the tradeoffs before proposing your next step.", "Avoid assuming that a person's disability determines their abilities or needs. Discuss people as individuals and ask what support, adjustments or further information could make participation fair. Recognise the limits of your role and when to seek guidance."], station: "disability-in-medicine" },
  { title: "Discuss a hot topic with balance", tag: "HOT TOPICS", paragraphs: ["Separate what you know from what you would need to check. Explore the effects on patients, staff and the health service, and consider both potential benefits and concerns.", "For medicines, verify current evidence and official guidance before asserting indications, risks or availability. You are explaining how you think about an issue, rather than advising a patient on treatment."], station: "ozempic" },
  { title: "Make the station clock work for you", tag: "TECHNIQUE", paragraphs: ["Use reading time to identify the question and organise two or three points. During your answer, make a point, illustrate it, then explain why it matters. Leave room for follow-up questions.", "If you lose your thread, pause and return to the question. Use practice feedback to choose one specific improvement for your next attempt. Speech observations are optional coaching cues and do not determine your score."], station: "why-medicine" },
];
export function InterviewGuides() {
  return <div className="space-y-6"><section className="rounded-3xl bg-[#042724] p-8 text-white"><BookOpen size={30} className="text-[#b9f4db]" /><h2 className="mt-5 text-3xl font-bold">Give your thinking a little structure.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-teal-50/75">Short guides you can read, try, and return to after a station.</p></section><div className="grid gap-5 lg:grid-cols-2">{guides.map((guide) => <article key={guide.title} className="rounded-2xl border border-[#dce6e5] bg-white p-7"><p className="text-[10px] font-bold tracking-widest text-[#08787b]">{guide.tag}</p><h2 className="mt-3 text-xl font-bold">{guide.title}</h2>{guide.paragraphs.map((p) => <p key={p} className="mt-4 text-sm leading-7 text-[#526b72]">{p}</p>)}<Link href={`/phloemai/interviews/ai-interviews?station=${guide.station}`} className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#08787b]">Put it into practice <ArrowRight size={16} /></Link></article>)}</div></div>;
}
