import type { UCATQuestion } from "./ucatQuestionBank";

const financeStimulus = [
  "The table shows the annual interest rates offered by four savings providers.",
  "Simple interest = P x N x R / 100. Compound interest = P x (1 + R / 100)^N - P. P is the amount invested, N is the number of years and R is the annual interest rate.",
];

const financeVisual = {
  type: "table" as const,
  title: "Savings providers",
  headers: ["Provider", "Annual interest rate"],
  rows: [
    ["A", "4%"],
    ["B", "7%"],
    ["C", "5%"],
    ["D", "9%"],
  ],
};

const marksStimulus = [
  "The table shows the number of candidates who achieved at least each mark threshold in an examination. The maximum mark was 100.",
];

const marksVisual = {
  type: "table" as const,
  title: "Examination marks",
  headers: ["Marks", "Number of candidates"],
  rows: [
    ["80 and above", "36"],
    ["70 and above", "84"],
    ["60 and above", "120"],
    ["50 and above", "150"],
    ["0 and above", "180"],
  ],
};

const workStimulus = [
  "The table shows the percentage of a software project completed by five contractors and the number of days each contractor worked.",
];

const workVisual = {
  type: "table" as const,
  title: "Project work",
  headers: ["Contractor", "Days worked", "Work completed"],
  rows: [
    ["A", "8", "20%"],
    ["B", "5", "15%"],
    ["C", "10", "30%"],
    ["D", "8", "25%"],
    ["E", "4", "10%"],
  ],
};

const payrollStimulus = [
  "The table shows annual salary data for four employee grades. A bonus may be paid as a percentage of annual salary.",
];

const payrollVisual = {
  type: "table" as const,
  title: "Employee salaries and bonuses",
  headers: ["Grade", "Employees", "Annual salary", "Bonus"],
  rows: [
    ["Trainee", "20", "24,000 pounds", "10%"],
    ["Supervisor", "8", "30,000 pounds", "20%"],
    ["Manager", "5", "48,000 pounds", "25%"],
    ["Executive", "2", "70,000 pounds", "50%"],
  ],
};

const cityStimulus = [
  "The table shows population data for five towns. A dash means the value is not directly given.",
];

const cityVisual = {
  type: "table" as const,
  title: "Town population data",
  headers: ["Town", "Population", "Rural:Urban", "Literate:Illiterate", "Graduates"],
  rows: [
    ["Harford", "-", "5:7", "4:1", "-"],
    ["Eldon", "720,000", "2:3", "-", "45%"],
    ["Marlow", "-", "4:5", "3:2", "-"],
    ["Kingsport", "540,000", "7:8", "-", "60%"],
    ["Ashbridge", "-", "1:4", "5:3", "-"],
  ],
};

const groupedBarStimulus = [
  "The grouped bar chart shows the number of literate males and females in three states.",
];

const groupedBarVisual = {
  type: "grouped-bar" as const,
  title: "Literate population by state",
  yLabel: "People",
  max: 800,
  seriesLabels: ["Male", "Female"],
  groups: [
    { label: "A", values: [460, 380] },
    { label: "B", values: [520, 650] },
    { label: "C", values: [720, 430] },
  ],
};

const roomStimulus = [
  "The table shows the dimensions, in metres, of three rooms. Each room has four walls and no windows, doors or other wall openings.",
  "Each room has two walls of length x height and two walls of breadth x height.",
];

const roomVisual = {
  type: "table" as const,
  title: "Room dimensions",
  headers: ["Dimension", "Room A", "Room B", "Room C"],
  rows: [
    ["Length", "12", "14", "18"],
    ["Breadth", "9", "8", "12"],
    ["Height", "4", "5", "4"],
  ],
};

const professionStimulus = [
  "A survey was conducted in a city with a population of 20,000, asking people for their profession and origin.",
  "A dash means the value is not directly given.",
];

const professionVisual = {
  type: "table" as const,
  title: "Profession and origin survey",
  headers: ["Profession", "People", "British origin", "Foreign origin"],
  rows: [
    ["Medical", "12%", "60%", "-"],
    ["Engineering", "-", "-", "55%"],
    ["Banking", "18%", "50%", "-"],
    ["Law", "10%", "-", "45%"],
    ["Teaching", "15%", "70%", "-"],
    ["Management", "-", "-", "52%"],
  ],
};

const holidayStimulus = [
  "Nia, Omar and Priya are saving for a revision trip. The trip costs 4,800 pounds.",
  "Nia will pay 30% of the total cost. Omar and Priya will split the remaining cost in a 5:3 ratio.",
];

const cupcakeStimulus = [
  "A bakery made 9 batches of cupcakes, with each batch containing 14 cupcakes.",
  "One-third of the cupcakes were chocolate. Customers then bought all 18 strawberry cupcakes. The only cupcakes left were vanilla and raspberry, and there were 16 more vanilla cupcakes than raspberry cupcakes.",
];

const marksBySubjectStimulus = [
  "The table shows marks obtained by three students in four subjects. The maximum mark for each subject is 100.",
];

const marksBySubjectVisual = {
  type: "table" as const,
  title: "Subject marks",
  headers: ["Student", "Mathematics", "AI", "English", "Physical Education"],
  rows: [
    ["Amira", "82", "74", "68", "96"],
    ["Theo", "75", "88", "54", "83"],
    ["Lina", "90", "70", "80", "60"],
  ],
};

const clinicStimulus = [
  "The table shows appointment data for a clinic on one day.",
];

const clinicVisual = {
  type: "table" as const,
  title: "Clinic appointments",
  headers: ["Appointment type", "Appointments", "Average duration", "Fee"],
  rows: [
    ["GP", "24", "12 min", "48 pounds"],
    ["Nurse", "30", "10 min", "28 pounds"],
    ["Physio", "12", "35 min", "60 pounds"],
    ["Blood test", "45", "6 min", "15 pounds"],
  ],
};

const busStimulus = [
  "The table shows data for four shuttle routes. The same route is repeated continuously during the day.",
];

const busVisual = {
  type: "table" as const,
  title: "Shuttle routes",
  headers: ["Route", "Distance", "Journey time", "Passengers per journey"],
  rows: [
    ["A", "12 km", "24 min", "36"],
    ["B", "18 km", "27 min", "45"],
    ["C", "20 km", "40 min", "50"],
    ["D", "15 km", "20 min", "30"],
  ],
};

const dosageStimulus = [
  "An oral medicine contains 125 mg of active ingredient in each 5 mL.",
  "The required daily dose is 10 mg per kg of body mass, split into two equal doses. Each bottle contains 150 mL.",
];

const dosageVisual = {
  type: "table" as const,
  title: "Patient masses",
  headers: ["Patient", "Mass"],
  rows: [
    ["A", "24 kg"],
    ["B", "30 kg"],
    ["C", "45 kg"],
    ["D", "60 kg"],
  ],
};

const cateringStimulus = [
  "The table shows ingredients and costs for preparing 24 portions of a meal.",
];

const cateringVisual = {
  type: "table" as const,
  title: "Meal ingredients",
  headers: ["Item", "Amount for 24 portions", "Cost"],
  rows: [
    ["Pasta", "1.8 kg", "2.20 pounds per kg"],
    ["Sauce", "3.0 L", "1.50 pounds per L"],
    ["Cheese", "600 g", "8.00 pounds per kg"],
    ["Trays", "3", "1.20 pounds each"],
  ],
};

const retailStimulus = [
  "The table shows cost prices, selling prices and units sold for four products.",
];

const retailVisual = {
  type: "table" as const,
  title: "Shop sales",
  headers: ["Product", "Cost price", "Selling price", "Units sold"],
  rows: [
    ["Notebook", "3.00 pounds", "5.00 pounds", "120"],
    ["Pen set", "1.50 pounds", "3.00 pounds", "200"],
    ["Flask", "6.00 pounds", "10.00 pounds", "80"],
    ["Tote bag", "4.00 pounds", "7.00 pounds", "90"],
  ],
};

const energyStimulus = [
  "The line chart shows household electricity use from January to June.",
  "Electricity costs 0.28 pounds per kWh, plus a standing charge of 18 pounds per month.",
];

const energyVisual = {
  type: "line" as const,
  title: "Electricity use",
  yLabel: "kWh",
  max: 450,
  points: [
    { label: "Jan", value: 420 },
    { label: "Feb", value: 390 },
    { label: "Mar", value: 360 },
    { label: "Apr", value: 300 },
    { label: "May", value: 270 },
    { label: "Jun", value: 240 },
  ],
};

const gymStimulus = [
  "The table shows membership options at a fitness centre.",
];

const gymVisual = {
  type: "table" as const,
  title: "Gym plans",
  headers: ["Plan", "Monthly fee", "Joining fee"],
  rows: [
    ["Basic", "22 pounds", "20 pounds"],
    ["Premium", "34 pounds", "0 pounds"],
    ["Student", "18 pounds", "10 pounds"],
    ["Family", "55 pounds", "30 pounds"],
  ],
};

const packagingStimulus = [
  "The table shows the internal dimensions and cost of three types of cardboard box.",
];

const packagingVisual = {
  type: "table" as const,
  title: "Box dimensions",
  headers: ["Box", "Length", "Width", "Height", "Cost"],
  rows: [
    ["Small", "20 cm", "15 cm", "10 cm", "0.40 pounds"],
    ["Medium", "30 cm", "20 cm", "15 cm", "0.70 pounds"],
    ["Large", "40 cm", "25 cm", "20 cm", "1.10 pounds"],
  ],
};

const labStimulus = [
  "A laboratory records samples, processing time per sample and the number of machines available. Machines share work equally and process continuously.",
];

const labVisual = {
  type: "table" as const,
  title: "Laboratory processing",
  headers: ["Test type", "Samples", "Minutes per sample", "Machines"],
  rows: [
    ["Haematology", "180", "2", "3"],
    ["Chemistry", "120", "3", "2"],
    ["Microbiology", "90", "5", "3"],
    ["Immunology", "140", "4", "5"],
  ],
};

const cinemaStimulus = [
  "A group is booking cinema tickets. The group has 8 adults, 12 students and 10 children.",
  "Weekend screenings add a surcharge of 1.50 pounds per ticket. There is one 2.00 pounds booking fee per order.",
];

const cinemaVisual = {
  type: "table" as const,
  title: "Cinema ticket prices",
  headers: ["Ticket type", "Base price"],
  rows: [
    ["Adult", "12.50 pounds"],
    ["Student", "9.00 pounds"],
    ["Child", "7.00 pounds"],
  ],
};

const warehouseStimulus = [
  "The table shows stock held in a supplies warehouse. Damaged stock cannot be used.",
];

const warehouseVisual = {
  type: "table" as const,
  title: "Warehouse stock",
  headers: ["Item", "Units in stock", "Damaged", "Unit value"],
  rows: [
    ["Gloves", "2,400", "5%", "0.25 pounds"],
    ["Masks", "1,800", "8%", "0.40 pounds"],
    ["Gowns", "950", "4%", "3.20 pounds"],
    ["Visors", "600", "12%", "1.50 pounds"],
  ],
};

const routeStimulus = [
  "A walking map uses a scale of 1 cm to 0.8 km. Walking speed on flat ground is 5 km per hour.",
  "Add 1 minute for each 10 m of climb.",
];

const routeVisual = {
  type: "table" as const,
  title: "Walking routes",
  headers: ["Route", "Map length", "Climb"],
  rows: [
    ["A", "12.5 cm", "75 m"],
    ["B", "9.0 cm", "120 m"],
    ["C", "15.0 cm", "60 m"],
    ["D", "10.5 cm", "90 m"],
  ],
};

const gardenStimulus = [
  "The table shows dimensions for a garden plan. Use pi = 3.14 for the circular pond.",
  "A gravel path area equal to 20% of the total rectangular bed area is added.",
];

const gardenVisual = {
  type: "table" as const,
  title: "Garden plan",
  headers: ["Area", "Dimensions"],
  rows: [
    ["Rose bed", "6 m by 4 m"],
    ["Herb bed", "5 m by 3 m"],
    ["Vegetable bed", "8 m by 5 m"],
    ["Pond", "radius 2 m"],
  ],
};

const mobileStimulus = [
  "The table shows monthly mobile data plans. Extra data costs 2.00 pounds per GB unless otherwise stated.",
];

const mobileVisual = {
  type: "table" as const,
  title: "Mobile data plans",
  headers: ["Plan", "Included data", "Monthly price"],
  rows: [
    ["Mini", "6 GB", "8 pounds"],
    ["Plus", "15 GB", "15 pounds"],
    ["Max", "40 GB", "32 pounds"],
    ["Family", "100 GB", "70 pounds"],
  ],
};

export const ORIGINAL_QR_QUESTIONS: UCATQuestion[] = [
  {
    id: "qr-bank-finance-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-savings-providers",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: financeStimulus,
    visual: financeVisual,
    question:
      "Provider B pays compound interest. If 18,000 pounds is deposited with provider B, how much will be in the account after 1 year?",
    options: [
      { key: "A", text: "1,260 pounds" },
      { key: "B", text: "18,700 pounds" },
      { key: "C", text: "19,260 pounds" },
      { key: "D", text: "19,620 pounds" },
    ],
    answer: "C",
    explanation:
      "One year of 7% interest gives 18,000 x 1.07 = 19,260 pounds.",
  },
  {
    id: "qr-bank-finance-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-savings-providers",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: financeStimulus,
    visual: financeVisual,
    question:
      "A saver invests money with provider A for 2 years. Compound interest would give 48 pounds more than simple interest. How much did the saver invest?",
    options: [
      { key: "A", text: "1,200 pounds" },
      { key: "B", text: "12,000 pounds" },
      { key: "C", text: "24,000 pounds" },
      { key: "D", text: "30,000 pounds" },
    ],
    answer: "D",
    explanation:
      "At 4% for 2 years, compound gives 8.16% interest and simple gives 8%. The difference is 0.16% of P. So 0.0016P = 48, giving P = 30,000.",
  },
  {
    id: "qr-bank-finance-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-savings-providers",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: financeStimulus,
    visual: financeVisual,
    question:
      "A saver uses provider C, which pays simple interest. After 3 years, the account contains 27,600 pounds. What was the original deposit?",
    options: [
      { key: "A", text: "20,000 pounds" },
      { key: "B", text: "22,400 pounds" },
      { key: "C", text: "24,000 pounds" },
      { key: "D", text: "25,000 pounds" },
    ],
    answer: "C",
    explanation:
      "Simple interest at 5% for 3 years adds 15%, so the final amount is 1.15P. 27,600 / 1.15 = 24,000.",
  },
  {
    id: "qr-bank-finance-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-savings-providers",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: financeStimulus,
    visual: financeVisual,
    question:
      "A saver deposits 12,000 pounds with provider B using simple interest for 2 years, and the same amount with provider D using compound interest for 2 years. How much greater is the interest from provider D?",
    options: [
      { key: "A", text: "457.20 pounds" },
      { key: "B", text: "520.00 pounds" },
      { key: "C", text: "577.20 pounds" },
      { key: "D", text: "681.00 pounds" },
    ],
    answer: "C",
    explanation:
      "Provider B simple interest is 12,000 x 7% x 2 = 1,680. Provider D compound interest is 12,000 x (1.09^2 - 1) = 2,257.20. The difference is 577.20 pounds.",
  },
  {
    id: "qr-bank-thresholds-001",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-exam-thresholds",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksStimulus,
    visual: marksVisual,
    question: "How many candidates scored at least 50 marks but below 70?",
    options: [
      { key: "A", text: "30" },
      { key: "B", text: "36" },
      { key: "C", text: "48" },
      { key: "D", text: "66" },
    ],
    answer: "D",
    explanation:
      "At least 50 is 150 candidates and at least 70 is 84 candidates. The number from 50 to below 70 is 150 - 84 = 66.",
  },
  {
    id: "qr-bank-thresholds-002",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-exam-thresholds",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksStimulus,
    visual: marksVisual,
    question: "What percentage of candidates scored at least 70 marks?",
    options: [
      { key: "A", text: "36.0%" },
      { key: "B", text: "46.7%" },
      { key: "C", text: "60.0%" },
      { key: "D", text: "66.7%" },
    ],
    answer: "B",
    explanation:
      "84 out of 180 candidates scored at least 70. 84 / 180 x 100 = 46.7%.",
  },
  {
    id: "qr-bank-thresholds-003",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-exam-thresholds",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksStimulus,
    visual: marksVisual,
    question:
      "If the pass mark is 60 marks, what percentage of candidates failed the examination?",
    options: [
      { key: "A", text: "20.0%" },
      { key: "B", text: "30.0%" },
      { key: "C", text: "33.3%" },
      { key: "D", text: "40.0%" },
    ],
    answer: "C",
    explanation:
      "120 candidates scored at least 60, so 180 - 120 = 60 failed. 60 / 180 = 33.3%.",
  },
  {
    id: "qr-bank-thresholds-004",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-exam-thresholds",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksStimulus,
    visual: marksVisual,
    question:
      "What is the ratio of candidates who scored below 70 marks to candidates who scored at least 50 marks?",
    options: [
      { key: "A", text: "8:15" },
      { key: "B", text: "14:25" },
      { key: "C", text: "16:25" },
      { key: "D", text: "25:16" },
    ],
    answer: "C",
    explanation:
      "Below 70 is 180 - 84 = 96 candidates. At least 50 is 150 candidates. The ratio 96:150 simplifies to 16:25.",
  },
  {
    id: "qr-bank-work-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-project-work",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: workStimulus,
    visual: workVisual,
    question:
      "What is the ratio of work completed by contractor D in one day to work completed by contractor E in one day?",
    options: [
      { key: "A", text: "3:2" },
      { key: "B", text: "4:5" },
      { key: "C", text: "5:4" },
      { key: "D", text: "5:2" },
    ],
    answer: "C",
    explanation:
      "D completes 25% in 8 days = 3.125% per day. E completes 10% in 4 days = 2.5% per day. The ratio 3.125:2.5 simplifies to 5:4.",
  },
  {
    id: "qr-bank-work-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-project-work",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: workStimulus,
    visual: workVisual,
    question:
      "Contractors A and B work together for 8 days, then contractor C completes the remaining work. How many days does C take?",
    options: [
      { key: "A", text: "14 2/3 days" },
      { key: "B", text: "16 days" },
      { key: "C", text: "18 2/3 days" },
      { key: "D", text: "20 days" },
    ],
    answer: "C",
    explanation:
      "A works at 20/8 = 2.5% per day and B works at 15/5 = 3% per day. In 8 days they complete 44%, leaving 56%. C works at 30/10 = 3% per day, so 56 / 3 = 18 2/3 days.",
  },
  {
    id: "qr-bank-work-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-project-work",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: workStimulus,
    visual: workVisual,
    question:
      "If only contractors D and E complete a full project together, how long will they take?",
    options: [
      { key: "A", text: "15 1/2 days" },
      { key: "B", text: "16 4/9 days" },
      { key: "C", text: "17 7/9 days" },
      { key: "D", text: "18 2/3 days" },
    ],
    answer: "C",
    explanation:
      "D and E together complete 25/8 + 10/4 = 5.625% per day. 100 / 5.625 = 17.777..., which is 17 7/9 days.",
  },
  {
    id: "qr-bank-work-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-project-work",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: workStimulus,
    visual: workVisual,
    question:
      "A new contractor F completes 15 percentage points more work in 12 days than contractor C completes in 10 days. How many days would F take to complete the whole project alone?",
    options: [
      { key: "A", text: "22 1/2 days" },
      { key: "B", text: "24 days" },
      { key: "C", text: "26 2/3 days" },
      { key: "D", text: "30 days" },
    ],
    answer: "C",
    explanation:
      "C completes 30% in 10 days. F completes 30% + 15% = 45% in 12 days, so F's rate is 3.75% per day. 100 / 3.75 = 26 2/3 days.",
  },
  {
    id: "qr-bank-payroll-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-payroll-bonus",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: payrollStimulus,
    visual: payrollVisual,
    question:
      "What is the minimum total amount required to pay the trainee salaries for one year?",
    options: [
      { key: "A", text: "240,000 pounds" },
      { key: "B", text: "360,000 pounds" },
      { key: "C", text: "420,000 pounds" },
      { key: "D", text: "480,000 pounds" },
    ],
    answer: "D",
    explanation:
      "There are 20 trainees and each salary is 24,000 pounds. 20 x 24,000 = 480,000 pounds.",
  },
  {
    id: "qr-bank-payroll-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-payroll-bonus",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: payrollStimulus,
    visual: payrollVisual,
    question: "If everyone earned the bonus, what would be the total bonuses paid?",
    options: [
      { key: "A", text: "118,000 pounds" },
      { key: "B", text: "156,000 pounds" },
      { key: "C", text: "196,000 pounds" },
      { key: "D", text: "226,000 pounds" },
    ],
    answer: "D",
    explanation:
      "Bonuses are 48,000 for trainees, 48,000 for supervisors, 60,000 for managers and 70,000 for executives. The total is 226,000 pounds.",
  },
  {
    id: "qr-bank-payroll-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-payroll-bonus",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: payrollStimulus,
    visual: payrollVisual,
    question:
      "What is the percentage increase in a supervisor's bonus if the supervisor salary rises to 36,000 pounds and the bonus rate stays the same?",
    options: [
      { key: "A", text: "10%" },
      { key: "B", text: "16.7%" },
      { key: "C", text: "20%" },
      { key: "D", text: "25%" },
    ],
    answer: "C",
    explanation:
      "The supervisor bonus rises from 20% of 30,000 = 6,000 to 20% of 36,000 = 7,200. The increase is 1,200 / 6,000 = 20%.",
  },
  {
    id: "qr-bank-payroll-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-payroll-bonus",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: payrollStimulus,
    visual: payrollVisual,
    question:
      "What is the change in the maximum possible bonuses if four new trainees join the company and one manager leaves?",
    options: [
      { key: "A", text: "Decrease of 12,000 pounds" },
      { key: "B", text: "Decrease of 2,400 pounds" },
      { key: "C", text: "No change" },
      { key: "D", text: "Increase of 2,400 pounds" },
    ],
    answer: "B",
    explanation:
      "Four new trainees add 4 x 2,400 = 9,600 pounds of possible bonus. One manager leaving removes 12,000 pounds of possible bonus. Net change is a decrease of 2,400 pounds.",
  },
  {
    id: "qr-bank-cities-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-town-demographics",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cityStimulus,
    visual: cityVisual,
    question:
      "The combined population of Harford and Marlow is 1,080,000. Marlow has 120,000 more people than Harford. What is the urban population of Harford?",
    options: [
      { key: "A", text: "200,000" },
      { key: "B", text: "280,000" },
      { key: "C", text: "320,000" },
      { key: "D", text: "480,000" },
    ],
    answer: "B",
    explanation:
      "Harford has (1,080,000 - 120,000) / 2 = 480,000 people. With rural:urban = 5:7, urban Harford is 7/12 x 480,000 = 280,000.",
  },
  {
    id: "qr-bank-cities-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-town-demographics",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cityStimulus,
    visual: cityVisual,
    question: "What is the combined rural population of Eldon and Kingsport?",
    options: [
      { key: "A", text: "288,000" },
      { key: "B", text: "360,000" },
      { key: "C", text: "540,000" },
      { key: "D", text: "612,000" },
    ],
    answer: "C",
    explanation:
      "Eldon's rural population is 2/5 x 720,000 = 288,000. Kingsport's rural population is 7/15 x 540,000 = 252,000. Together, this is 540,000.",
  },
  {
    id: "qr-bank-cities-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-town-demographics",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cityStimulus,
    visual: cityVisual,
    question:
      "A census shows that one-third of Marlow's population is 200,000. How many illiterate people are there in Marlow?",
    options: [
      { key: "A", text: "120,000" },
      { key: "B", text: "200,000" },
      { key: "C", text: "240,000" },
      { key: "D", text: "360,000" },
    ],
    answer: "C",
    explanation:
      "Marlow's population is 200,000 x 3 = 600,000. With literate:illiterate = 3:2, illiterate people are 2/5 x 600,000 = 240,000.",
  },
  {
    id: "qr-bank-cities-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-town-demographics",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cityStimulus,
    visual: cityVisual,
    question:
      "If the number of graduates in Marlow is one-quarter of the number of graduates in Eldon, what is the difference between the number of graduates in Kingsport and Marlow?",
    options: [
      { key: "A", text: "81,000" },
      { key: "B", text: "162,000" },
      { key: "C", text: "210,000" },
      { key: "D", text: "243,000" },
    ],
    answer: "D",
    explanation:
      "Eldon graduates = 45% of 720,000 = 324,000. Marlow graduates = 324,000 / 4 = 81,000. Kingsport graduates = 60% of 540,000 = 324,000. The difference is 243,000.",
  },
  {
    id: "qr-bank-bars-001",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-literate-population",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: groupedBarStimulus,
    visual: groupedBarVisual,
    question: "From all three states, what is the total number of literate females?",
    options: [
      { key: "A", text: "1,150" },
      { key: "B", text: "1,320" },
      { key: "C", text: "1,460" },
      { key: "D", text: "1,700" },
    ],
    answer: "C",
    explanation:
      "The female totals are 380, 650 and 430. Their total is 1,460.",
  },
  {
    id: "qr-bank-bars-002",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-literate-population",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: groupedBarStimulus,
    visual: groupedBarVisual,
    question: "What percentage of literate people in State B are female?",
    options: [
      { key: "A", text: "44%" },
      { key: "B", text: "52%" },
      { key: "C", text: "56%" },
      { key: "D", text: "60%" },
    ],
    answer: "C",
    explanation:
      "State B has 520 literate males and 650 literate females, for a total of 1,170. 650 / 1,170 x 100 = 55.6%, which rounds to 56%.",
  },
  {
    id: "qr-bank-bars-003",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-literate-population",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: groupedBarStimulus,
    visual: groupedBarVisual,
    question:
      "What is the ratio of literate females in State A to literate males in State C?",
    options: [
      { key: "A", text: "19:36" },
      { key: "B", text: "36:19" },
      { key: "C", text: "3:5" },
      { key: "D", text: "5:9" },
    ],
    answer: "A",
    explanation:
      "The required ratio is 380:720. Dividing by 20 gives 19:36.",
  },
  {
    id: "qr-bank-bars-004",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-literate-population",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: groupedBarStimulus,
    visual: groupedBarVisual,
    question:
      "What is the average total number of literate people per state, rounded to the nearest whole number?",
    options: [
      { key: "A", text: "983" },
      { key: "B", text: "1,033" },
      { key: "C", text: "1,053" },
      { key: "D", text: "1,170" },
    ],
    answer: "C",
    explanation:
      "The state totals are 840, 1,170 and 1,150. Their total is 3,160, and 3,160 / 3 = 1,053.3, which rounds to 1,053.",
  },
  {
    id: "qr-bank-geometry-001",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-room-walls",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: roomStimulus,
    visual: roomVisual,
    question: "What is the total wall area of Room A?",
    options: [
      { key: "A", text: "84 m2" },
      { key: "B", text: "96 m2" },
      { key: "C", text: "144 m2" },
      { key: "D", text: "168 m2" },
    ],
    answer: "D",
    explanation:
      "Wall area = 2 x height x (length + breadth). For Room A, this is 2 x 4 x (12 + 9) = 168 m2.",
  },
  {
    id: "qr-bank-geometry-002",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-room-walls",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: roomStimulus,
    visual: roomVisual,
    question: "What is the ratio of the wall area of Room A to Room B to Room C?",
    options: [
      { key: "A", text: "21:22:30" },
      { key: "B", text: "42:55:60" },
      { key: "C", text: "55:42:60" },
      { key: "D", text: "12:14:18" },
    ],
    answer: "B",
    explanation:
      "The wall areas are 168, 220 and 240 m2. Dividing by 4 gives the simplified ratio 42:55:60.",
  },
  {
    id: "qr-bank-geometry-003",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-room-walls",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: roomStimulus,
    visual: roomVisual,
    question:
      "One tin of paint covers 20 m2. How many tins are needed to give Room B two coats of paint?",
    options: [
      { key: "A", text: "11 tins" },
      { key: "B", text: "18 tins" },
      { key: "C", text: "20 tins" },
      { key: "D", text: "22 tins" },
    ],
    answer: "D",
    explanation:
      "Room B wall area is 2 x 5 x (14 + 8) = 220 m2. Two coats cover 440 m2, and 440 / 20 = 22 tins.",
  },
  {
    id: "qr-bank-geometry-004",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-room-walls",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: roomStimulus,
    visual: roomVisual,
    question:
      "Rooms A and C are painted at 6.50 pounds per m2. A 12% discount is then applied to the total cost. What is the final cost?",
    options: [
      { key: "A", text: "2,121.60 pounds" },
      { key: "B", text: "2,333.76 pounds" },
      { key: "C", text: "2,446.08 pounds" },
      { key: "D", text: "2,652.00 pounds" },
    ],
    answer: "B",
    explanation:
      "Rooms A and C have wall areas 168 and 240 m2, total 408 m2. Cost before discount = 408 x 6.50 = 2,652. A 12% discount leaves 88%, so final cost = 2,652 x 0.88 = 2,333.76 pounds.",
  },
  {
    id: "qr-bank-survey-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-profession-origin",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: professionStimulus,
    visual: professionVisual,
    question: "How many people of foreign origin are in the medical profession?",
    options: [
      { key: "A", text: "720" },
      { key: "B", text: "960" },
      { key: "C", text: "1,200" },
      { key: "D", text: "1,440" },
    ],
    answer: "B",
    explanation:
      "Medical workers are 12% of 20,000 = 2,400. If 60% are of British origin, 40% are of foreign origin. 40% of 2,400 is 960.",
  },
  {
    id: "qr-bank-survey-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-profession-origin",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: professionStimulus,
    visual: professionVisual,
    question:
      "What is the ratio of people of foreign origin in banking to people of British origin in law?",
    options: [
      { key: "A", text: "9:11" },
      { key: "B", text: "11:18" },
      { key: "C", text: "18:11" },
      { key: "D", text: "25:18" },
    ],
    answer: "C",
    explanation:
      "Banking is 18% of 20,000 = 3,600 people, and 50% are of foreign origin = 1,800. Law is 10% of 20,000 = 2,000 people, and 55% are of British origin = 1,100. The ratio 1,800:1,100 simplifies to 18:11.",
  },
  {
    id: "qr-bank-survey-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-profession-origin",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: professionStimulus,
    visual: professionVisual,
    question:
      "If Management accounts for 20% of the population, then the number of people in Banking is what fraction of the number of people in Engineering?",
    options: [
      { key: "A", text: "2/5" },
      { key: "B", text: "18/25" },
      { key: "C", text: "20/27" },
      { key: "D", text: "25/18" },
    ],
    answer: "B",
    explanation:
      "The given profession percentages total 55%. If Management is 20%, Engineering must be 25%. Banking is 18%, so Banking as a fraction of Engineering is 18/25.",
  },
  {
    id: "qr-bank-survey-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-profession-origin",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: professionStimulus,
    visual: professionVisual,
    question:
      "Engineering accounts for 9 percentage points more of the population than Management. What is the difference between the number of foreign-origin people in Management and British-origin people in Engineering?",
    options: [
      { key: "A", text: "170" },
      { key: "B", text: "360" },
      { key: "C", text: "558" },
      { key: "D", text: "729" },
    ],
    answer: "C",
    explanation:
      "Engineering plus Management is 45% of the population. If Engineering is 9 percentage points higher, Management is 18% and Engineering is 27%. Foreign-origin Management = 20,000 x 18% x 52% = 1,872. British-origin Engineering = 20,000 x 27% x 45% = 2,430. The difference is 558.",
  },
  {
    id: "qr-bank-holiday-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-revision-trip",
    tags: ["text-stem", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: holidayStimulus,
    question: "How much will Omar pay?",
    options: [
      { key: "A", text: "1,440 pounds" },
      { key: "B", text: "1,680 pounds" },
      { key: "C", text: "2,100 pounds" },
      { key: "D", text: "2,700 pounds" },
    ],
    answer: "C",
    explanation:
      "Nia pays 30%, so Omar and Priya split 70% of 4,800 = 3,360 pounds. Omar gets 5/8 of this, which is 2,100 pounds.",
  },
  {
    id: "qr-bank-holiday-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-revision-trip",
    tags: ["text-stem", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: holidayStimulus,
    question:
      "Nia saves 24 pounds per week. How long must she save to pay her share?",
    options: [
      { key: "A", text: "48 weeks" },
      { key: "B", text: "52 weeks" },
      { key: "C", text: "60 weeks" },
      { key: "D", text: "1 year and 20 weeks" },
    ],
    answer: "C",
    explanation:
      "Nia's share is 30% of 4,800 = 1,440 pounds. At 24 pounds per week, she needs 1,440 / 24 = 60 weeks.",
  },
  {
    id: "qr-bank-holiday-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-revision-trip",
    tags: [
      "text-stem",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: holidayStimulus,
    question:
      "A service charge makes up 12% of the trip cost. If 40% of the service charge goes to the booking agent, how much does the agent receive?",
    options: [
      { key: "A", text: "192.00 pounds" },
      { key: "B", text: "230.40 pounds" },
      { key: "C", text: "288.00 pounds" },
      { key: "D", text: "480.00 pounds" },
    ],
    answer: "B",
    explanation:
      "The service charge is 12% of 4,800 = 576 pounds. The agent receives 40% of this, which is 230.40 pounds.",
  },
  {
    id: "qr-bank-holiday-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-revision-trip",
    tags: [
      "text-stem",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: holidayStimulus,
    question:
      "The trip price rises by 6% after Nia has already paid her original share. Omar and Priya split the new remaining cost in the same 5:3 ratio. How much more does Omar pay than originally planned?",
    options: [
      { key: "A", text: "96 pounds" },
      { key: "B", text: "144 pounds" },
      { key: "C", text: "180 pounds" },
      { key: "D", text: "288 pounds" },
    ],
    answer: "C",
    explanation:
      "The new trip cost is 4,800 x 1.06 = 5,088 pounds. Nia has paid 1,440 pounds, leaving 3,648. Omar pays 5/8 of 3,648 = 2,280 pounds, which is 180 pounds more than his original 2,100 pounds.",
  },
  {
    id: "qr-bank-cupcakes-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-cupcake-batches",
    tags: ["text-stem", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: cupcakeStimulus,
    question: "How many cupcakes were made in total?",
    options: [
      { key: "A", text: "96" },
      { key: "B", text: "108" },
      { key: "C", text: "118" },
      { key: "D", text: "126" },
    ],
    answer: "D",
    explanation: "9 batches of 14 cupcakes gives 9 x 14 = 126 cupcakes.",
  },
  {
    id: "qr-bank-cupcakes-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-cupcake-batches",
    tags: ["text-stem", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: cupcakeStimulus,
    question: "How many chocolate cupcakes were made?",
    options: [
      { key: "A", text: "36" },
      { key: "B", text: "40" },
      { key: "C", text: "42" },
      { key: "D", text: "48" },
    ],
    answer: "C",
    explanation: "One-third of 126 is 42.",
  },
  {
    id: "qr-bank-cupcakes-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-cupcake-batches",
    tags: ["text-stem", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: cupcakeStimulus,
    question: "How many raspberry cupcakes were left?",
    options: [
      { key: "A", text: "21" },
      { key: "B", text: "25" },
      { key: "C", text: "33" },
      { key: "D", text: "41" },
    ],
    answer: "B",
    explanation:
      "After 42 chocolate and 18 strawberry cupcakes, 66 cupcakes remain. If raspberry is R and vanilla is R + 16, then 2R + 16 = 66, so R = 25.",
  },
  {
    id: "qr-bank-cupcakes-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-cupcake-batches",
    tags: [
      "text-stem",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Stem",
    stimulus: cupcakeStimulus,
    question:
      "If each remaining raspberry cupcake is sold for 2.40 pounds and each remaining vanilla cupcake for 2.10 pounds, what is the total revenue from the remaining cupcakes?",
    options: [
      { key: "A", text: "126.60 pounds" },
      { key: "B", text: "138.00 pounds" },
      { key: "C", text: "146.10 pounds" },
      { key: "D", text: "158.40 pounds" },
    ],
    answer: "C",
    explanation:
      "There are 25 raspberry and 41 vanilla cupcakes. Revenue = 25 x 2.40 + 41 x 2.10 = 60.00 + 86.10 = 146.10 pounds.",
  },
  {
    id: "qr-bank-marks-001",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-subject-marks",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksBySubjectStimulus,
    visual: marksBySubjectVisual,
    question: "What is Amira's total mark?",
    options: [
      { key: "A", text: "300" },
      { key: "B", text: "310" },
      { key: "C", text: "320" },
      { key: "D", text: "330" },
    ],
    answer: "C",
    explanation: "Amira's total is 82 + 74 + 68 + 96 = 320.",
  },
  {
    id: "qr-bank-marks-002",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-subject-marks",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksBySubjectStimulus,
    visual: marksBySubjectVisual,
    question:
      "What is the difference between Amira's and Theo's overall percentages?",
    options: [
      { key: "A", text: "4 percentage points" },
      { key: "B", text: "5 percentage points" },
      { key: "C", text: "8 percentage points" },
      { key: "D", text: "12 percentage points" },
    ],
    answer: "B",
    explanation:
      "Amira scores 320/400 = 80%. Theo scores 300/400 = 75%. The difference is 5 percentage points.",
  },
  {
    id: "qr-bank-marks-003",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-subject-marks",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksBySubjectStimulus,
    visual: marksBySubjectVisual,
    question:
      "Lina takes a fifth subject. What mark does she need in that subject to have an average of 78 across five subjects?",
    options: [
      { key: "A", text: "70" },
      { key: "B", text: "78" },
      { key: "C", text: "80" },
      { key: "D", text: "90" },
    ],
    answer: "D",
    explanation:
      "Lina's current total is 90 + 70 + 80 + 60 = 300. A five-subject average of 78 needs 390 total marks, so she needs 90.",
  },
  {
    id: "qr-bank-marks-004",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-subject-marks",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: marksBySubjectStimulus,
    visual: marksBySubjectVisual,
    question:
      "Theo's English mark increases by 20% of its original value, but his Physical Education mark decreases by 10%. What is his new overall percentage, to the nearest 0.1%?",
    options: [
      { key: "A", text: "74.6%" },
      { key: "B", text: "75.0%" },
      { key: "C", text: "75.6%" },
      { key: "D", text: "76.2%" },
    ],
    answer: "C",
    explanation:
      "Theo's new English mark is 54 x 1.2 = 64.8 and his new PE mark is 83 x 0.9 = 74.7. His new total is 75 + 88 + 64.8 + 74.7 = 302.5, so his percentage is 302.5 / 400 x 100 = 75.6%.",
  },
  {
    id: "qr-bank-clinic-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-clinic-appointments",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: clinicStimulus,
    visual: clinicVisual,
    question: "What is the total revenue from GP appointments?",
    options: [
      { key: "A", text: "576 pounds" },
      { key: "B", text: "960 pounds" },
      { key: "C", text: "1,152 pounds" },
      { key: "D", text: "1,440 pounds" },
    ],
    answer: "C",
    explanation: "GP revenue is 24 appointments x 48 pounds = 1,152 pounds.",
  },
  {
    id: "qr-bank-clinic-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-clinic-appointments",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: clinicStimulus,
    visual: clinicVisual,
    question: "How many hours of nurse appointments are scheduled?",
    options: [
      { key: "A", text: "3 hours" },
      { key: "B", text: "4 hours" },
      { key: "C", text: "5 hours" },
      { key: "D", text: "6 hours" },
    ],
    answer: "C",
    explanation:
      "Nurse appointments take 30 x 10 = 300 minutes, which is 5 hours.",
  },
  {
    id: "qr-bank-clinic-003",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-clinic-appointments",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: clinicStimulus,
    visual: clinicVisual,
    question:
      "What is the average fee per appointment across all appointments, to the nearest penny?",
    options: [
      { key: "A", text: "28.00 pounds" },
      { key: "B", text: "30.51 pounds" },
      { key: "C", text: "32.25 pounds" },
      { key: "D", text: "33.87 pounds" },
    ],
    answer: "B",
    explanation:
      "Total revenue is 1,152 + 840 + 720 + 675 = 3,387 pounds. Total appointments are 111. Average fee = 3,387 / 111 = 30.51 pounds.",
  },
  {
    id: "qr-bank-clinic-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-clinic-appointments",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: clinicStimulus,
    visual: clinicVisual,
    question:
      "If blood test appointments increase by 20% and physio appointments decrease by 25%, what is the net change in revenue?",
    options: [
      { key: "A", text: "Decrease of 180 pounds" },
      { key: "B", text: "Decrease of 45 pounds" },
      { key: "C", text: "No change" },
      { key: "D", text: "Increase of 45 pounds" },
    ],
    answer: "B",
    explanation:
      "Blood tests increase by 9 appointments, adding 9 x 15 = 135 pounds. Physio appointments decrease by 3 appointments, removing 3 x 60 = 180 pounds. Net change is a decrease of 45 pounds.",
  },
  {
    id: "qr-bank-bus-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-shuttle-routes",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: busStimulus,
    visual: busVisual,
    question: "Which route has the greatest average speed?",
    options: [
      { key: "A", text: "Route A" },
      { key: "B", text: "Route B" },
      { key: "C", text: "Route C" },
      { key: "D", text: "Route D" },
    ],
    answer: "D",
    explanation:
      "Route D covers 15 km in 20 minutes, which is 45 km per hour. This is faster than routes A, B and C.",
  },
  {
    id: "qr-bank-bus-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-shuttle-routes",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: busStimulus,
    visual: busVisual,
    question: "At the stated rate, how many passengers does Route B carry per hour?",
    options: [
      { key: "A", text: "75" },
      { key: "B", text: "90" },
      { key: "C", text: "100" },
      { key: "D", text: "108" },
    ],
    answer: "C",
    explanation:
      "Route B carries 45 passengers in 27 minutes. In 60 minutes, this is 45 x 60 / 27 = 100 passengers.",
  },
  {
    id: "qr-bank-bus-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-shuttle-routes",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: busStimulus,
    visual: busVisual,
    question:
      "If Route A's distance increases by 25% but its average speed stays the same, what is the new journey time?",
    options: [
      { key: "A", text: "26 minutes" },
      { key: "B", text: "28 minutes" },
      { key: "C", text: "30 minutes" },
      { key: "D", text: "32 minutes" },
    ],
    answer: "C",
    explanation:
      "At the same speed, journey time increases by the same 25%. 24 x 1.25 = 30 minutes.",
  },
  {
    id: "qr-bank-bus-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-shuttle-routes",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: busStimulus,
    visual: busVisual,
    question:
      "Route C charges 2.40 pounds per passenger. If its journey time is reduced by 10 minutes and passenger numbers rise by 16%, what is the revenue per hour?",
    options: [
      { key: "A", text: "232.00 pounds" },
      { key: "B", text: "250.80 pounds" },
      { key: "C", text: "278.40 pounds" },
      { key: "D", text: "288.00 pounds" },
    ],
    answer: "C",
    explanation:
      "Passenger numbers become 50 x 1.16 = 58. Revenue per journey is 58 x 2.40 = 139.20 pounds. With a 30-minute journey, this is two journeys per hour, so revenue is 278.40 pounds per hour.",
  },
  {
    id: "qr-bank-dosage-001",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-medicine-dose",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: dosageStimulus,
    visual: dosageVisual,
    question: "What is Patient B's required daily dose?",
    options: [
      { key: "A", text: "150 mg" },
      { key: "B", text: "250 mg" },
      { key: "C", text: "300 mg" },
      { key: "D", text: "450 mg" },
    ],
    answer: "C",
    explanation: "Patient B has mass 30 kg, so the daily dose is 30 x 10 = 300 mg.",
  },
  {
    id: "qr-bank-dosage-002",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-medicine-dose",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: dosageStimulus,
    visual: dosageVisual,
    question: "How many mL should Patient C receive in each dose?",
    options: [
      { key: "A", text: "4.5 mL" },
      { key: "B", text: "9 mL" },
      { key: "C", text: "12 mL" },
      { key: "D", text: "18 mL" },
    ],
    answer: "B",
    explanation:
      "Patient C needs 45 x 10 = 450 mg per day, or 225 mg per dose. The medicine contains 25 mg per mL, so 225 / 25 = 9 mL.",
  },
  {
    id: "qr-bank-dosage-003",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-medicine-dose",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: dosageStimulus,
    visual: dosageVisual,
    question: "How many days will one bottle last for Patient D?",
    options: [
      { key: "A", text: "5.25 days" },
      { key: "B", text: "6.25 days" },
      { key: "C", text: "7.5 days" },
      { key: "D", text: "10 days" },
    ],
    answer: "B",
    explanation:
      "Patient D needs 600 mg per day. At 25 mg per mL, this is 24 mL per day. One bottle lasts 150 / 24 = 6.25 days.",
  },
  {
    id: "qr-bank-dosage-004",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-medicine-dose",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: dosageStimulus,
    visual: dosageVisual,
    question:
      "What is the maximum number of full days that all four patients can be supplied from three full bottles?",
    options: [
      { key: "A", text: "5 days" },
      { key: "B", text: "6 days" },
      { key: "C", text: "7 days" },
      { key: "D", text: "8 days" },
    ],
    answer: "C",
    explanation:
      "Daily volumes are 9.6, 12, 18 and 24 mL, totalling 63.6 mL per day. Three bottles contain 450 mL. 450 / 63.6 = 7.07, so only 7 full days are possible.",
  },
  {
    id: "qr-bank-catering-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-catering-scale",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cateringStimulus,
    visual: cateringVisual,
    question: "How much sauce is needed for 60 portions?",
    options: [
      { key: "A", text: "5.0 L" },
      { key: "B", text: "6.0 L" },
      { key: "C", text: "7.5 L" },
      { key: "D", text: "9.0 L" },
    ],
    answer: "C",
    explanation:
      "60 portions is 60 / 24 = 2.5 times the recipe. Sauce needed = 3.0 x 2.5 = 7.5 L.",
  },
  {
    id: "qr-bank-catering-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-catering-scale",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cateringStimulus,
    visual: cateringVisual,
    question: "What is the cost of the cheese needed for 96 portions?",
    options: [
      { key: "A", text: "9.60 pounds" },
      { key: "B", text: "14.40 pounds" },
      { key: "C", text: "19.20 pounds" },
      { key: "D", text: "24.00 pounds" },
    ],
    answer: "C",
    explanation:
      "96 portions is 4 times the recipe, so cheese needed is 2.4 kg. At 8.00 pounds per kg, the cost is 19.20 pounds.",
  },
  {
    id: "qr-bank-catering-003",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-catering-scale",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cateringStimulus,
    visual: cateringVisual,
    question:
      "What is the ingredient and tray cost per portion for 24 portions, to the nearest penny?",
    options: [
      { key: "A", text: "0.58 pounds" },
      { key: "B", text: "0.70 pounds" },
      { key: "C", text: "0.83 pounds" },
      { key: "D", text: "1.41 pounds" },
    ],
    answer: "B",
    explanation:
      "The total cost for 24 portions is 3.96 + 4.50 + 4.80 + 3.60 = 16.86 pounds. Cost per portion = 16.86 / 24 = 0.70 pounds.",
  },
  {
    id: "qr-bank-catering-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-catering-scale",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cateringStimulus,
    visual: cateringVisual,
    question:
      "For 180 portions, an 8% waste allowance is added to the pasta amount. How much pasta should be bought, to the nearest 0.1 kg?",
    options: [
      { key: "A", text: "13.5 kg" },
      { key: "B", text: "14.0 kg" },
      { key: "C", text: "14.6 kg" },
      { key: "D", text: "15.0 kg" },
    ],
    answer: "C",
    explanation:
      "180 portions is 7.5 times the recipe, so pasta before waste is 1.8 x 7.5 = 13.5 kg. Adding 8% gives 13.5 x 1.08 = 14.58 kg, which rounds to 14.6 kg.",
  },
  {
    id: "qr-bank-retail-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-shop-sales",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: retailStimulus,
    visual: retailVisual,
    question: "What is the total revenue from pen sets?",
    options: [
      { key: "A", text: "300 pounds" },
      { key: "B", text: "450 pounds" },
      { key: "C", text: "600 pounds" },
      { key: "D", text: "750 pounds" },
    ],
    answer: "C",
    explanation: "Revenue from pen sets is 200 x 3.00 = 600 pounds.",
  },
  {
    id: "qr-bank-retail-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-shop-sales",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: retailStimulus,
    visual: retailVisual,
    question: "What is the total profit from notebooks?",
    options: [
      { key: "A", text: "120 pounds" },
      { key: "B", text: "180 pounds" },
      { key: "C", text: "240 pounds" },
      { key: "D", text: "360 pounds" },
    ],
    answer: "C",
    explanation:
      "Profit per notebook is 5.00 - 3.00 = 2.00 pounds. Total profit is 120 x 2.00 = 240 pounds.",
  },
  {
    id: "qr-bank-retail-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-shop-sales",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: retailStimulus,
    visual: retailVisual,
    question:
      "What is the overall profit margin as a percentage of revenue, to the nearest whole percent?",
    options: [
      { key: "A", text: "34%" },
      { key: "B", text: "39%" },
      { key: "C", text: "43%" },
      { key: "D", text: "57%" },
    ],
    answer: "C",
    explanation:
      "Total revenue is 2,630 pounds and total cost is 1,500 pounds, so profit is 1,130 pounds. Profit margin = 1,130 / 2,630 x 100 = 43%.",
  },
  {
    id: "qr-bank-retail-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-shop-sales",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: retailStimulus,
    visual: retailVisual,
    question:
      "During a sale, the flask selling price falls by 15% and units sold rise by 25%. What is the change in total flask profit?",
    options: [
      { key: "A", text: "Decrease of 70 pounds" },
      { key: "B", text: "Decrease of 40 pounds" },
      { key: "C", text: "No change" },
      { key: "D", text: "Increase of 40 pounds" },
    ],
    answer: "A",
    explanation:
      "Original flask profit is (10.00 - 6.00) x 80 = 320 pounds. New selling price is 8.50 pounds and new units sold are 100, so new profit is (8.50 - 6.00) x 100 = 250 pounds. Profit decreases by 70 pounds.",
  },
  {
    id: "qr-bank-energy-001",
    section: "qr",
    subtype: "qr-graphs",
    setId: "qr-bank-electricity-use",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: energyStimulus,
    visual: energyVisual,
    question: "How many kWh were used in March and April combined?",
    options: [
      { key: "A", text: "570 kWh" },
      { key: "B", text: "600 kWh" },
      { key: "C", text: "630 kWh" },
      { key: "D", text: "660 kWh" },
    ],
    answer: "D",
    explanation: "March and April usage total 360 + 300 = 660 kWh.",
  },
  {
    id: "qr-bank-energy-002",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-electricity-use",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: energyStimulus,
    visual: energyVisual,
    question: "What was the average monthly electricity use from January to June?",
    options: [
      { key: "A", text: "300 kWh" },
      { key: "B", text: "315 kWh" },
      { key: "C", text: "330 kWh" },
      { key: "D", text: "345 kWh" },
    ],
    answer: "C",
    explanation:
      "Total use is 420 + 390 + 360 + 300 + 270 + 240 = 1,980 kWh. Average = 1,980 / 6 = 330 kWh.",
  },
  {
    id: "qr-bank-energy-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-electricity-use",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: energyStimulus,
    visual: energyVisual,
    question: "What was the electricity bill for May?",
    options: [
      { key: "A", text: "75.60 pounds" },
      { key: "B", text: "83.60 pounds" },
      { key: "C", text: "93.60 pounds" },
      { key: "D", text: "96.00 pounds" },
    ],
    answer: "C",
    explanation:
      "May usage cost is 270 x 0.28 = 75.60 pounds. Adding the 18 pounds standing charge gives 93.60 pounds.",
  },
  {
    id: "qr-bank-energy-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-electricity-use",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Graph",
    stimulus: energyStimulus,
    visual: energyVisual,
    question:
      "In July, usage is 12.5% lower than in June. The tariff rises to 0.31 pounds per kWh and the standing charge becomes 20 pounds. What is the July bill?",
    options: [
      { key: "A", text: "80.10 pounds" },
      { key: "B", text: "85.10 pounds" },
      { key: "C", text: "89.44 pounds" },
      { key: "D", text: "93.60 pounds" },
    ],
    answer: "B",
    explanation:
      "July usage is 240 x 0.875 = 210 kWh. Usage cost is 210 x 0.31 = 65.10 pounds. Adding 20 pounds gives 85.10 pounds.",
  },
  {
    id: "qr-bank-gym-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-gym-plans",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gymStimulus,
    visual: gymVisual,
    question: "What is the total cost of the Basic plan for 6 months?",
    options: [
      { key: "A", text: "132 pounds" },
      { key: "B", text: "142 pounds" },
      { key: "C", text: "152 pounds" },
      { key: "D", text: "164 pounds" },
    ],
    answer: "C",
    explanation:
      "Six months of Basic costs 6 x 22 = 132 pounds, plus the 20 pounds joining fee, making 152 pounds.",
  },
  {
    id: "qr-bank-gym-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-gym-plans",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gymStimulus,
    visual: gymVisual,
    question:
      "How much more does the Premium plan cost than the Basic plan over 12 months?",
    options: [
      { key: "A", text: "104 pounds" },
      { key: "B", text: "124 pounds" },
      { key: "C", text: "144 pounds" },
      { key: "D", text: "164 pounds" },
    ],
    answer: "B",
    explanation:
      "Premium costs 12 x 34 = 408 pounds. Basic costs 12 x 22 + 20 = 284 pounds. The difference is 124 pounds.",
  },
  {
    id: "qr-bank-gym-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-gym-plans",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gymStimulus,
    visual: gymVisual,
    question:
      "A member pays 226 pounds in total on the Student plan. How many months of membership did this cover?",
    options: [
      { key: "A", text: "10 months" },
      { key: "B", text: "11 months" },
      { key: "C", text: "12 months" },
      { key: "D", text: "13 months" },
    ],
    answer: "C",
    explanation:
      "After the 10 pounds joining fee, 216 pounds remains for monthly fees. 216 / 18 = 12 months.",
  },
  {
    id: "qr-bank-gym-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-gym-plans",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gymStimulus,
    visual: gymVisual,
    question:
      "A family of four takes the Family plan for 8 months. How much do they save compared with each person taking the Basic plan separately for 8 months?",
    options: [
      { key: "A", text: "254 pounds" },
      { key: "B", text: "284 pounds" },
      { key: "C", text: "314 pounds" },
      { key: "D", text: "344 pounds" },
    ],
    answer: "C",
    explanation:
      "Four separate Basic plans cost 4 x (20 + 8 x 22) = 784 pounds. One Family plan costs 30 + 8 x 55 = 470 pounds. The saving is 314 pounds.",
  },
  {
    id: "qr-bank-packaging-001",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-box-dimensions",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: packagingStimulus,
    visual: packagingVisual,
    question: "What is the internal volume of a Small box?",
    options: [
      { key: "A", text: "300 cm3" },
      { key: "B", text: "1,500 cm3" },
      { key: "C", text: "3,000 cm3" },
      { key: "D", text: "4,500 cm3" },
    ],
    answer: "C",
    explanation: "Small box volume = 20 x 15 x 10 = 3,000 cm3.",
  },
  {
    id: "qr-bank-packaging-002",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-box-dimensions",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: packagingStimulus,
    visual: packagingVisual,
    question: "What is the ratio of the volume of a Small box to a Medium box?",
    options: [
      { key: "A", text: "1:2" },
      { key: "B", text: "1:3" },
      { key: "C", text: "2:3" },
      { key: "D", text: "3:1" },
    ],
    answer: "B",
    explanation:
      "A Small box is 3,000 cm3 and a Medium box is 30 x 20 x 15 = 9,000 cm3. The ratio 3,000:9,000 simplifies to 1:3.",
  },
  {
    id: "qr-bank-packaging-003",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-box-dimensions",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: packagingStimulus,
    visual: packagingVisual,
    question:
      "How many Medium boxes are needed to hold 162,000 cm3 of items if there is no wasted space?",
    options: [
      { key: "A", text: "12" },
      { key: "B", text: "16" },
      { key: "C", text: "18" },
      { key: "D", text: "20" },
    ],
    answer: "C",
    explanation:
      "Each Medium box holds 9,000 cm3. 162,000 / 9,000 = 18 boxes.",
  },
  {
    id: "qr-bank-packaging-004",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-box-dimensions",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: packagingStimulus,
    visual: packagingVisual,
    question:
      "Large boxes are filled to 80% of their internal volume. How many Large boxes are needed to pack 2.5 m3 of items?",
    options: [
      { key: "A", text: "125" },
      { key: "B", text: "150" },
      { key: "C", text: "156" },
      { key: "D", text: "157" },
    ],
    answer: "D",
    explanation:
      "A Large box has volume 40 x 25 x 20 = 20,000 cm3 = 0.02 m3. Filled to 80%, each holds 0.016 m3. 2.5 / 0.016 = 156.25, so 157 boxes are needed.",
  },
  {
    id: "qr-bank-lab-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-lab-processing",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: labStimulus,
    visual: labVisual,
    question: "How many total minutes of work are required for Chemistry samples?",
    options: [
      { key: "A", text: "240 minutes" },
      { key: "B", text: "300 minutes" },
      { key: "C", text: "360 minutes" },
      { key: "D", text: "420 minutes" },
    ],
    answer: "C",
    explanation: "Chemistry requires 120 samples x 3 minutes = 360 minutes of work.",
  },
  {
    id: "qr-bank-lab-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-lab-processing",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: labStimulus,
    visual: labVisual,
    question: "How long will Haematology take with its available machines?",
    options: [
      { key: "A", text: "90 minutes" },
      { key: "B", text: "100 minutes" },
      { key: "C", text: "120 minutes" },
      { key: "D", text: "180 minutes" },
    ],
    answer: "C",
    explanation:
      "Haematology requires 180 x 2 = 360 minutes of work. With 3 machines, the time is 360 / 3 = 120 minutes.",
  },
  {
    id: "qr-bank-lab-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-lab-processing",
    tags: ["data-display", "set-based", "medium", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: labStimulus,
    visual: labVisual,
    question: "Which test type will finish first with the available machines?",
    options: [
      { key: "A", text: "Haematology" },
      { key: "B", text: "Chemistry" },
      { key: "C", text: "Microbiology" },
      { key: "D", text: "Immunology" },
    ],
    answer: "D",
    explanation:
      "Processing times are Haematology 120 minutes, Chemistry 180 minutes, Microbiology 150 minutes and Immunology 112 minutes. Immunology finishes first.",
  },
  {
    id: "qr-bank-lab-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-lab-processing",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: labStimulus,
    visual: labVisual,
    question:
      "Chemistry receives two extra machines, but its number of samples increases by 20%. How much time is saved compared with the original Chemistry processing time?",
    options: [
      { key: "A", text: "48 minutes" },
      { key: "B", text: "60 minutes" },
      { key: "C", text: "72 minutes" },
      { key: "D", text: "90 minutes" },
    ],
    answer: "C",
    explanation:
      "Chemistry originally takes 360 / 2 = 180 minutes. New samples = 144, giving 144 x 3 = 432 minutes of work. With 4 machines, time is 432 / 4 = 108 minutes, saving 72 minutes.",
  },
  {
    id: "qr-bank-cinema-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-cinema-tickets",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cinemaStimulus,
    visual: cinemaVisual,
    question: "What is the base ticket cost for all adults in the group?",
    options: [
      { key: "A", text: "80 pounds" },
      { key: "B", text: "90 pounds" },
      { key: "C", text: "100 pounds" },
      { key: "D", text: "108 pounds" },
    ],
    answer: "C",
    explanation: "There are 8 adults at 12.50 pounds each, so the cost is 100 pounds.",
  },
  {
    id: "qr-bank-cinema-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-cinema-tickets",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cinemaStimulus,
    visual: cinemaVisual,
    question:
      "What is the total group ticket cost for a weekend screening before the booking fee?",
    options: [
      { key: "A", text: "278 pounds" },
      { key: "B", text: "300 pounds" },
      { key: "C", text: "323 pounds" },
      { key: "D", text: "325 pounds" },
    ],
    answer: "C",
    explanation:
      "Base ticket cost is 100 + 108 + 70 = 278 pounds. There are 30 tickets, so the weekend surcharge is 30 x 1.50 = 45 pounds. Total before booking fee is 323 pounds.",
  },
  {
    id: "qr-bank-cinema-003",
    section: "qr",
    subtype: "qr-averages",
    setId: "qr-bank-cinema-tickets",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cinemaStimulus,
    visual: cinemaVisual,
    question:
      "Including the weekend surcharge and booking fee, what is the average cost per ticket?",
    options: [
      { key: "A", text: "9.27 pounds" },
      { key: "B", text: "10.50 pounds" },
      { key: "C", text: "10.77 pounds" },
      { key: "D", text: "10.83 pounds" },
    ],
    answer: "D",
    explanation:
      "The total including booking fee is 323 + 2 = 325 pounds. There are 30 tickets, so average cost = 325 / 30 = 10.83 pounds.",
  },
  {
    id: "qr-bank-cinema-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-cinema-tickets",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: cinemaStimulus,
    visual: cinemaVisual,
    question:
      "A 15% discount is applied to base ticket prices only. The weekend surcharge and booking fee are unchanged. What is the total amount paid?",
    options: [
      { key: "A", text: "236.30 pounds" },
      { key: "B", text: "281.30 pounds" },
      { key: "C", text: "283.30 pounds" },
      { key: "D", text: "295.55 pounds" },
    ],
    answer: "C",
    explanation:
      "Discounted base price is 278 x 0.85 = 236.30 pounds. Add the unchanged 45 pounds weekend surcharge and 2 pounds booking fee to get 283.30 pounds.",
  },
  {
    id: "qr-bank-warehouse-001",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-warehouse-stock",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: warehouseStimulus,
    visual: warehouseVisual,
    question: "How many gloves are undamaged?",
    options: [
      { key: "A", text: "120" },
      { key: "B", text: "2,160" },
      { key: "C", text: "2,280" },
      { key: "D", text: "2,360" },
    ],
    answer: "C",
    explanation:
      "5% of 2,400 gloves are damaged, so 95% are undamaged. 2,400 x 0.95 = 2,280.",
  },
  {
    id: "qr-bank-warehouse-002",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-warehouse-stock",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: warehouseStimulus,
    visual: warehouseVisual,
    question: "What is the value of the damaged masks?",
    options: [
      { key: "A", text: "28.80 pounds" },
      { key: "B", text: "57.60 pounds" },
      { key: "C", text: "72.00 pounds" },
      { key: "D", text: "144.00 pounds" },
    ],
    answer: "B",
    explanation:
      "8% of 1,800 masks are damaged, which is 144 masks. Their value is 144 x 0.40 = 57.60 pounds.",
  },
  {
    id: "qr-bank-warehouse-003",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-warehouse-stock",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: warehouseStimulus,
    visual: warehouseVisual,
    question: "What is the combined number of undamaged gowns and visors?",
    options: [
      { key: "A", text: "1,320" },
      { key: "B", text: "1,392" },
      { key: "C", text: "1,440" },
      { key: "D", text: "1,488" },
    ],
    answer: "C",
    explanation:
      "Undamaged gowns = 950 x 96% = 912. Undamaged visors = 600 x 88% = 528. Combined total = 1,440.",
  },
  {
    id: "qr-bank-warehouse-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-warehouse-stock",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: warehouseStimulus,
    visual: warehouseVisual,
    question: "What is the total value of all undamaged stock?",
    options: [
      { key: "A", text: "4,326.80 pounds" },
      { key: "B", text: "4,642.80 pounds" },
      { key: "C", text: "4,942.80 pounds" },
      { key: "D", text: "5,102.40 pounds" },
    ],
    answer: "C",
    explanation:
      "Undamaged stock values are gloves 570.00, masks 662.40, gowns 2,918.40 and visors 792.00 pounds. The total is 4,942.80 pounds.",
  },
  {
    id: "qr-bank-route-001",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-walking-map",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: routeStimulus,
    visual: routeVisual,
    question: "What is the actual distance of Route A?",
    options: [
      { key: "A", text: "7.5 km" },
      { key: "B", text: "9.0 km" },
      { key: "C", text: "10.0 km" },
      { key: "D", text: "12.5 km" },
    ],
    answer: "C",
    explanation: "Route A is 12.5 cm on the map. 12.5 x 0.8 = 10.0 km.",
  },
  {
    id: "qr-bank-route-002",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-walking-map",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: routeStimulus,
    visual: routeVisual,
    question: "What is the actual distance of Route C?",
    options: [
      { key: "A", text: "10.0 km" },
      { key: "B", text: "11.2 km" },
      { key: "C", text: "12.0 km" },
      { key: "D", text: "14.4 km" },
    ],
    answer: "C",
    explanation: "Route C is 15.0 cm on the map. 15.0 x 0.8 = 12.0 km.",
  },
  {
    id: "qr-bank-route-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-walking-map",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: routeStimulus,
    visual: routeVisual,
    question: "What is the estimated time for Route A?",
    options: [
      { key: "A", text: "120.0 minutes" },
      { key: "B", text: "125.5 minutes" },
      { key: "C", text: "127.5 minutes" },
      { key: "D", text: "132.0 minutes" },
    ],
    answer: "C",
    explanation:
      "Route A is 10 km. At 5 km per hour, this takes 2 hours = 120 minutes. The 75 m climb adds 7.5 minutes, so the total is 127.5 minutes.",
  },
  {
    id: "qr-bank-route-004",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-walking-map",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: routeStimulus,
    visual: routeVisual,
    question:
      "How much longer is Route C estimated to take than Route B?",
    options: [
      { key: "A", text: "39.6 minutes" },
      { key: "B", text: "45.6 minutes" },
      { key: "C", text: "51.6 minutes" },
      { key: "D", text: "57.6 minutes" },
    ],
    answer: "C",
    explanation:
      "Route B is 7.2 km, taking 86.4 minutes, plus 12 minutes climb = 98.4 minutes. Route C is 12 km, taking 144 minutes, plus 6 minutes climb = 150 minutes. The difference is 51.6 minutes.",
  },
  {
    id: "qr-bank-garden-001",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-garden-plan",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gardenStimulus,
    visual: gardenVisual,
    question: "What is the area of the vegetable bed?",
    options: [
      { key: "A", text: "13 m2" },
      { key: "B", text: "24 m2" },
      { key: "C", text: "32 m2" },
      { key: "D", text: "40 m2" },
    ],
    answer: "D",
    explanation: "The vegetable bed area is 8 x 5 = 40 m2.",
  },
  {
    id: "qr-bank-garden-002",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-garden-plan",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gardenStimulus,
    visual: gardenVisual,
    question: "What is the total area of the three rectangular beds?",
    options: [
      { key: "A", text: "64 m2" },
      { key: "B", text: "72 m2" },
      { key: "C", text: "79 m2" },
      { key: "D", text: "91 m2" },
    ],
    answer: "C",
    explanation:
      "The rectangular bed areas are 24, 15 and 40 m2. Their total is 79 m2.",
  },
  {
    id: "qr-bank-garden-003",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-garden-plan",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gardenStimulus,
    visual: gardenVisual,
    question:
      "Gravel costs 3.20 pounds per m2. What is the cost of gravel for the path?",
    options: [
      { key: "A", text: "25.28 pounds" },
      { key: "B", text: "45.60 pounds" },
      { key: "C", text: "50.56 pounds" },
      { key: "D", text: "63.20 pounds" },
    ],
    answer: "C",
    explanation:
      "The rectangular bed area is 79 m2, so the path area is 20% of 79 = 15.8 m2. Gravel cost = 15.8 x 3.20 = 50.56 pounds.",
  },
  {
    id: "qr-bank-garden-004",
    section: "qr",
    subtype: "qr-units-geometry",
    setId: "qr-bank-garden-plan",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: gardenStimulus,
    visual: gardenVisual,
    question:
      "What is the total area of the rectangular beds, pond and added path?",
    options: [
      { key: "A", text: "91.56 m2" },
      { key: "B", text: "95.36 m2" },
      { key: "C", text: "101.16 m2" },
      { key: "D", text: "107.36 m2" },
    ],
    answer: "D",
    explanation:
      "Rectangular beds total 79 m2. The pond area is 3.14 x 2 x 2 = 12.56 m2. The path area is 15.8 m2. Total area = 79 + 12.56 + 15.8 = 107.36 m2.",
  },
  {
    id: "qr-bank-mobile-001",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-mobile-data",
    tags: ["data-display", "set-based", "easy", "quick"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: mobileStimulus,
    visual: mobileVisual,
    question: "What is the monthly cost per GB for the Plus plan?",
    options: [
      { key: "A", text: "0.80 pounds" },
      { key: "B", text: "1.00 pound" },
      { key: "C", text: "1.20 pounds" },
      { key: "D", text: "1.50 pounds" },
    ],
    answer: "B",
    explanation: "The Plus plan costs 15 pounds for 15 GB, so it is 1 pound per GB.",
  },
  {
    id: "qr-bank-mobile-002",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-mobile-data",
    tags: ["data-display", "set-based", "easy", "multi-step"],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: mobileStimulus,
    visual: mobileVisual,
    question:
      "A user needs 18 GB for one month. What is the cheapest monthly cost?",
    options: [
      { key: "A", text: "15 pounds" },
      { key: "B", text: "18 pounds" },
      { key: "C", text: "21 pounds" },
      { key: "D", text: "32 pounds" },
    ],
    answer: "C",
    explanation:
      "The cheapest option is Plus with 3 GB extra data: 15 + 3 x 2 = 21 pounds. Max would cost 32 pounds.",
  },
  {
    id: "qr-bank-mobile-003",
    section: "qr",
    subtype: "qr-rates-ratios",
    setId: "qr-bank-mobile-data",
    tags: [
      "data-display",
      "set-based",
      "medium",
      "calculator-heavy",
      "multi-step",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: mobileStimulus,
    visual: mobileVisual,
    question:
      "Four users need 12 GB, 18 GB, 25 GB and 30 GB. How much do they save by choosing the Family plan instead of the cheapest separate plans?",
    options: [
      { key: "A", text: "18 pounds" },
      { key: "B", text: "24 pounds" },
      { key: "C", text: "30 pounds" },
      { key: "D", text: "38 pounds" },
    ],
    answer: "C",
    explanation:
      "The cheapest separate costs are 15, 21, 32 and 32 pounds, totalling 100 pounds. The Family plan costs 70 pounds, so the saving is 30 pounds.",
  },
  {
    id: "qr-bank-mobile-004",
    section: "qr",
    subtype: "qr-percentages",
    setId: "qr-bank-mobile-data",
    tags: [
      "data-display",
      "set-based",
      "hard",
      "calculator-heavy",
      "multi-step",
      "time-consuming",
    ],
    title: "Quantitative Reasoning Practice",
    leftTitle: "Table",
    stimulus: mobileStimulus,
    visual: mobileVisual,
    question:
      "Plan prices rise by 12.5%, but extra data falls to 1.50 pounds per GB. What is the new cheapest cost for a user needing 18 GB?",
    options: [
      { key: "A", text: "19.50 pounds" },
      { key: "B", text: "20.25 pounds" },
      { key: "C", text: "21.38 pounds" },
      { key: "D", text: "24.00 pounds" },
    ],
    answer: "C",
    explanation:
      "The raised Plus price is 15 x 1.125 = 16.875 pounds. Adding 3 GB of extra data costs 4.50 pounds, giving 21.375 pounds, or 21.38 pounds to the nearest penny.",
  },
];
