import type { UCATChartVisual, UCATQuestion } from "./ucatQuestionBank";

type ThreeSetCounts = {
  firstOnly: number;
  secondOnly: number;
  thirdOnly: number;
  firstSecond: number;
  firstThird: number;
  secondThird: number;
  allThree: number;
  neither?: number;
};

function threeSetDiagram(
  title: string,
  labels: readonly [string, string, string],
  counts: ThreeSetCounts
): UCATChartVisual {
  return {
    type: "set-diagram",
    title,
    shapes: [
      { id: "first", label: labels[0], shape: "pentagon", x: 36, y: 44, width: 180, height: 166 },
      { id: "second", label: labels[1], shape: "circle", x: 178, y: 88, width: 148, height: 138 },
      { id: "third", label: labels[2], shape: "triangle", x: 105, y: 28, width: 184, height: 210 },
    ],
    regionLabels: [
      { id: "first-only", text: String(counts.firstOnly), x: 84, y: 138 },
      { id: "second-only", text: String(counts.secondOnly), x: 286, y: 164 },
      { id: "third-only", text: String(counts.thirdOnly), x: 198, y: 70 },
      { id: "first-second", text: String(counts.firstSecond), x: 182, y: 166 },
      { id: "first-third", text: String(counts.firstThird), x: 142, y: 112 },
      { id: "second-third", text: String(counts.secondThird), x: 230, y: 126 },
      { id: "all-three", text: String(counts.allThree), x: 190, y: 128 },
      ...(typeof counts.neither === "number"
        ? [{ id: "neither", text: String(counts.neither), x: 335, y: 230 }]
        : []),
    ],
    legend: [
      { label: labels[0], shape: "pentagon" },
      { label: labels[1], shape: "circle" },
      { label: labels[2], shape: "triangle" },
    ],
  };
}

export const ORIGINAL_DM_QUESTIONS: UCATQuestion[] = [
  {
    id: "dm-bank-syllogisms-001",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["easy", "quick", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "This lab badge is a visitor pass. All visitor passes are blue. Some blue items are recyclable.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "badge-blue", text: "This lab badge is blue.", answer: "Yes" },
      { id: "recyclable-visitors", text: "Some recyclable items are visitor passes.", answer: "No" },
      { id: "visitor-blue-exists", text: "At least one visitor pass is blue.", answer: "Yes" },
      { id: "all-blue-visitors", text: "All blue items are visitor passes.", answer: "No" },
      { id: "badge-recyclable", text: "This lab badge is recyclable.", answer: "No" },
    ],
    explanation:
      "The lab badge is a visitor pass, and all visitor passes are blue. The recyclable blue items do not have to be visitor passes, and nothing says the lab badge is recyclable.",
  },
  {
    id: "dm-bank-syllogisms-002",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["easy", "quick", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "The cedar bench is made of timber. Every timber item in the garden is varnished. Some varnished items are not benches.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "bench-varnished", text: "The cedar bench is varnished.", answer: "Yes" },
      { id: "some-varnished-benches", text: "Some varnished items are benches.", answer: "Yes" },
      { id: "all-varnished-timber", text: "Every varnished item is made of timber.", answer: "No" },
      { id: "some-timber-not-benches", text: "Some timber items are not benches.", answer: "No" },
      { id: "no-benches-unvarnished", text: "No benches are unvarnished.", answer: "No" },
    ],
    explanation:
      "The cedar bench exists, is made of timber, and therefore is varnished. The information does not reverse the timber-varnished relationship or describe all benches.",
  },
  {
    id: "dm-bank-syllogisms-003",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["easy", "multi-step", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "Every urgent referral is reviewed today. No referral reviewed today is missing a triage note. Some paediatric referrals are urgent.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "paeds-reviewed", text: "Some paediatric referrals are reviewed today.", answer: "Yes" },
      { id: "urgent-not-missing", text: "No urgent referral is missing a triage note.", answer: "Yes" },
      { id: "some-paeds-not-missing", text: "Some paediatric referrals are not missing a triage note.", answer: "Yes" },
      { id: "reviewed-urgent", text: "Every referral reviewed today is urgent.", answer: "No" },
      { id: "no-paeds-missing", text: "No paediatric referral is missing a triage note.", answer: "No" },
    ],
    explanation:
      "The urgent paediatric referrals are reviewed today, and reviewed referrals are not missing triage notes. The wider claims about all reviewed or all paediatric referrals are not guaranteed.",
  },
  {
    id: "dm-bank-syllogisms-004",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "All archive folders from Room 3 are digitised. Every digitised folder is either indexed or marked for review. No indexed folder is in the red cabinet. Some folders marked for review are fragile. All fragile folders are in the red cabinet.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "indexed-room3-not-red", text: "No Room 3 folder that is indexed is in the red cabinet.", answer: "Yes" },
      { id: "review-red", text: "Some folders marked for review are in the red cabinet.", answer: "Yes" },
      { id: "digitised-fragile", text: "Every digitised folder is fragile.", answer: "No" },
      { id: "room3-not-indexed-review", text: "A Room 3 folder that is not indexed must be marked for review.", answer: "Yes" },
      { id: "fragile-not-indexed", text: "No fragile folder is indexed.", answer: "Yes" },
    ],
    explanation:
      "Room 3 folders are digitised, so they are indexed or marked for review. Indexed folders cannot be in the red cabinet. Fragile folders are in the red cabinet, so they cannot be indexed.",
  },
  {
    id: "dm-bank-syllogisms-005",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "All city pass holders are gallery visitors. Some gallery visitors booked a workshop. All workshop bookers receive a wristband. No wristband recipient uses the express queue. Some express queue users are city pass holders.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "pass-not-workshop", text: "Some city pass holders did not book a workshop.", answer: "Yes" },
      { id: "workshop-not-express", text: "No workshop booker uses the express queue.", answer: "Yes" },
      { id: "gallery-wristband", text: "Some gallery visitors receive a wristband.", answer: "Yes" },
      { id: "all-gallery-pass", text: "All gallery visitors have city passes.", answer: "No" },
      { id: "some-express-gallery", text: "Some express queue users are gallery visitors.", answer: "Yes" },
    ],
    explanation:
      "Some express queue users are city pass holders, so they are gallery visitors. They cannot be workshop bookers because workshop bookers receive wristbands and wristband recipients do not use the express queue.",
  },
  {
    id: "dm-bank-syllogisms-006",
    section: "dm",
    subtype: "dm-syllogisms",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Syllogism",
    stimulus: [
      "In the festival team, all coordinators are trained marshals. Any trained marshal is either radio-certified or first-aid-certified. No radio-certified marshal works at the north gate. Some first-aid-certified marshals work at the north gate. All north gate staff wear green badges.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Answer each conclusion using only the information given.",
    yesNoStatements: [
      { id: "first-aid-green", text: "Some first-aid-certified marshals wear green badges.", answer: "Yes" },
      { id: "all-coordinators-radio", text: "All coordinators are radio-certified.", answer: "No" },
      { id: "north-coordinator-not-radio", text: "A coordinator who works at the north gate cannot be radio-certified.", answer: "Yes" },
      { id: "coord-not-first-aid-radio", text: "Any coordinator who is not first-aid-certified must be radio-certified.", answer: "Yes" },
      { id: "green-not-radio", text: "Some green badge wearers are not radio-certified.", answer: "Yes" },
    ],
    explanation:
      "The north gate first-aid marshals wear green badges and cannot be radio-certified. Coordinators are trained marshals, so if a coordinator is not first-aid-certified, the either/or rule leaves radio-certified.",
  },
  {
    id: "dm-bank-logic-001",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Lina, Omar, Priya and Sven arrive for a workshop at 9:00, 9:10, 9:20 and 9:30, one person at each time. Lina arrives after Omar but before Sven. Priya arrives 20 minutes before Sven.",
    ],
    question: "Who could have arrived at 9:00?",
    options: [
      { key: "A", text: "Omar only" },
      { key: "B", text: "Priya only" },
      { key: "C", text: "Either Omar or Priya" },
      { key: "D", text: "None of them" },
    ],
    answer: "A",
    explanation:
      "If Sven arrived at 9:20, Priya would be at 9:00, leaving no earlier time for Omar before Lina. Therefore Sven must be at 9:30, Priya at 9:10, Omar at 9:00 and Lina at 9:20.",
  },
  {
    id: "dm-bank-logic-002",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Four samples, Aloe, Birch, Cedar and Dune, are assigned to benches 1, 2, 3 and 4. Aloe is on a lower-numbered bench than Cedar, with at least one bench between them. Birch is on bench 2. Dune's technician is Noor. The other technicians are Hale, Ivan and Pia.",
    ],
    question: "Which sample and technician team could be assigned to bench 1?",
    options: [
      { key: "A", text: "Aloe and Hale" },
      { key: "B", text: "Aloe and Noor" },
      { key: "C", text: "Cedar and Hale" },
      { key: "D", text: "Cedar and Noor" },
    ],
    answer: "A",
    explanation:
      "Aloe can be on bench 1 with Cedar on bench 3 or 4. Cedar cannot be on bench 1, and Noor must be paired with Dune, not Aloe.",
  },
  {
    id: "dm-bank-logic-003",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Asha, Ben, Cleo, Deepa, Ewan and Farah sit around a circular table, all facing the centre. Deepa is opposite Ben. Asha sits immediately clockwise from Deepa. Ewan is closer to Deepa than to Ben.",
    ],
    question: "Who sits immediately clockwise from Asha?",
    options: [
      { key: "A", text: "Cleo" },
      { key: "B", text: "Farah" },
      { key: "C", text: "Ewan" },
      { key: "D", text: "Cannot tell" },
    ],
    answer: "D",
    explanation:
      "Ewan must be on the other side of Deepa from Asha. Cleo and Farah fill the two remaining seats, so either could be immediately clockwise from Asha.",
  },
  {
    id: "dm-bank-logic-004",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Players in a guessing game were ranked by how close their estimate was to the actual number of coins in a jar. Rank 1 is closest.",
    ],
    visual: {
      type: "table",
      title: "Coin jar guesses",
      headers: ["Rank", "Player", "Guess"],
      rows: [
        ["1", "Eva", "146"],
        ["2", "Noor", "151"],
        ["3", "Luis", "143"],
        ["4", "Kai", "154"],
        ["5", "Maya", "139"],
      ],
    },
    question: "How many coins were actually in the jar?",
    options: [
      { key: "A", text: "147" },
      { key: "B", text: "148" },
      { key: "C", text: "149" },
      { key: "D", text: "150" },
    ],
    answer: "B",
    explanation:
      "If the actual number was 148, the distances are 2, 3, 5, 6 and 9 in the ranked order shown. The other options do not preserve the ranking.",
  },
  {
    id: "dm-bank-logic-005",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Five textbooks, Anatomy, Biochemistry, Genetics, Pathology and Statistics, are placed on shelves 1 to 5 from top to bottom. Anatomy is immediately above Biochemistry. Genetics is below Pathology. Statistics is not on shelf 5. Biochemistry is not on shelf 2.",
    ],
    question: "Which textbook could be on shelf 1?",
    options: [
      { key: "A", text: "Statistics only" },
      { key: "B", text: "Pathology only" },
      { key: "C", text: "Either Statistics or Pathology" },
      { key: "D", text: "None of them" },
    ],
    answer: "C",
    explanation:
      "Anatomy cannot be on shelf 1 because that would put Biochemistry on shelf 2. Valid arrangements can place either Statistics or Pathology on shelf 1.",
  },
  {
    id: "dm-bank-logic-006",
    section: "dm",
    subtype: "dm-logic",
    tags: ["hard", "time-consuming", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Alba, Bao and Carys each use one lab, numbered 1, 2 and 3, and each performs one assay, X, Y or Z. Assay Y is in lab 3. Alba is not in lab 1. Bao's lab number is lower than the lab number of the Z assay. Carys does not perform assay Y.",
    ],
    question: "Who performs assay X?",
    options: [
      { key: "A", text: "Alba" },
      { key: "B", text: "Bao" },
      { key: "C", text: "Carys" },
      { key: "D", text: "More information is required" },
    ],
    answer: "B",
    explanation:
      "Y is in lab 3. Z must be in lab 2 so that Bao can be in a lower-numbered lab. Therefore Bao is in lab 1 and performs X.",
  },
  {
    id: "dm-bank-arguments-001",
    section: "dm",
    subtype: "dm-arguments",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Argument",
    stimulus: [
      "A college is considering whether all students should complete a basic first-aid workshop before graduation.",
    ],
    question: "Select the strongest argument from the statements below.",
    options: [
      { key: "A", text: "Yes, because it could help students respond safely in common emergencies." },
      { key: "B", text: "Yes, because certificates can look attractive on noticeboards." },
      { key: "C", text: "No, because classrooms are sometimes cold." },
      { key: "D", text: "No, because first-aid kits can be different colours." },
    ],
    answer: "A",
    explanation:
      "A directly links the proposal to a relevant safety benefit. The other statements are irrelevant or too weak.",
  },
  {
    id: "dm-bank-arguments-002",
    section: "dm",
    subtype: "dm-arguments",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Argument",
    stimulus: [
      "A cafe is considering whether to charge a small deposit for reusable takeaway cups.",
    ],
    question: "Select the strongest argument from the statements below.",
    options: [
      { key: "A", text: "Yes, because deposits may encourage customers to return cups and reduce disposable waste." },
      { key: "B", text: "Yes, because cups are easier to stack than plates." },
      { key: "C", text: "No, because some customers prefer blue cups." },
      { key: "D", text: "No, because coffee is usually served hot." },
    ],
    answer: "A",
    explanation:
      "A is relevant to the purpose of a deposit scheme. The other arguments do not meaningfully address the decision.",
  },
  {
    id: "dm-bank-arguments-003",
    section: "dm",
    subtype: "dm-arguments",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Argument",
    stimulus: [
      "A library is deciding whether phone calls should be prohibited in its silent study rooms.",
    ],
    question: "Select the strongest argument from the statements below.",
    options: [
      { key: "A", text: "Yes, because phone calls can disturb people who chose the room for quiet study." },
      { key: "B", text: "Yes, because phones have screens." },
      { key: "C", text: "No, because some library chairs have armrests." },
      { key: "D", text: "No, because many people own phones." },
    ],
    answer: "A",
    explanation:
      "A directly addresses the purpose of silent study rooms. The other options are irrelevant or do not justify a policy decision.",
  },
  {
    id: "dm-bank-arguments-004",
    section: "dm",
    subtype: "dm-arguments",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Argument",
    stimulus: [
      "A council is considering whether electric scooters should be allowed on crowded pavements.",
    ],
    question: "Select the strongest argument from the statements below.",
    options: [
      { key: "A", text: "Yes, because scooters are sometimes painted brightly." },
      { key: "B", text: "Yes, because some journeys are short." },
      { key: "C", text: "No, because fast scooters on crowded pavements could increase collision risk for pedestrians." },
      { key: "D", text: "No, because pavements are made from different materials." },
    ],
    answer: "C",
    explanation:
      "C gives a relevant safety reason tied directly to the proposal. The other options are weaker or irrelevant.",
  },
  {
    id: "dm-bank-arguments-005",
    section: "dm",
    subtype: "dm-arguments",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Argument",
    stimulus: [
      "A town is considering whether structurally safe unused office buildings should be converted into affordable flats.",
    ],
    question: "Select the strongest argument from the statements below.",
    options: [
      { key: "A", text: "Yes, because it could increase housing supply while reusing buildings that are already available." },
      { key: "B", text: "Yes, because old office carpets are usually patterned." },
      { key: "C", text: "No, because some offices have lifts." },
      { key: "D", text: "No, because people sometimes work from home." },
    ],
    answer: "A",
    explanation:
      "A addresses both housing need and practical reuse. The other arguments do not substantially engage with the proposal.",
  },
  {
    id: "dm-bank-yes-no-001",
    section: "dm",
    subtype: "dm-yes-no",
    tags: ["easy", "time-consuming", "multi-step", "data-display"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Data",
    stimulus: [
      "Four couriers recorded their working time and parcels delivered during one morning.",
    ],
    visual: {
      type: "table",
      title: "Courier deliveries",
      headers: ["Courier", "Time worked (hours)", "Parcels delivered"],
      rows: [
        ["A", "5", "65"],
        ["B", "4", "56"],
        ["C", "8", "88"],
        ["D", "6", "72"],
      ],
      note: "Delivery rate = parcels delivered divided by time worked.",
    },
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Use the table to answer each conclusion.",
    yesNoStatements: [
      { id: "b-highest", text: "Courier B had the highest delivery rate.", answer: "Yes" },
      { id: "no-same-rate", text: "No two couriers had the same delivery rate.", answer: "Yes" },
      { id: "c-more-than-d", text: "Courier C delivered more parcels than Courier D.", answer: "Yes" },
      { id: "a-lower-than-d", text: "Courier A had a lower delivery rate than Courier D.", answer: "No" },
      { id: "ab-more-cd", text: "Couriers A and B delivered more parcels in total than Couriers C and D.", answer: "No" },
    ],
    explanation:
      "The rates are A = 13, B = 14, C = 11 and D = 12 parcels per hour. C delivered 88 parcels, more than D's 72, but A and B total 121 while C and D total 160.",
  },
  {
    id: "dm-bank-yes-no-002",
    section: "dm",
    subtype: "dm-yes-no",
    tags: ["easy", "quick", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "At Brook Lane, an unused car park was converted into raised beds. Volunteers grow herbs and vegetables there, and surplus produce is donated to a lunch club. The project manager says it has reduced fly-tipping nearby, but council waste collection data has not yet been published. The garden is open on weekends only.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Use the paragraph to answer each conclusion.",
    yesNoStatements: [
      { id: "produce-donated", text: "Some produce from the garden is donated to a lunch club.", answer: "Yes" },
      { id: "waste-proves", text: "Published waste collection data proves that fly-tipping fell.", answer: "No" },
      { id: "open-every-day", text: "The garden is open every day.", answer: "No" },
      { id: "herbs-grown", text: "Volunteers grow herbs at Brook Lane.", answer: "Yes" },
      { id: "still-unused", text: "The car park remained unused after the conversion.", answer: "No" },
    ],
    explanation:
      "The paragraph states that surplus produce is donated, herbs are grown, and the garden opens only on weekends. The waste data has not yet been published.",
  },
  {
    id: "dm-bank-yes-no-003",
    section: "dm",
    subtype: "dm-yes-no",
    tags: ["medium", "multi-step", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A physiotherapy service offered video follow-ups for patients who did not need hands-on assessment. Travel reimbursements fell by 18% over three months. Missed appointments also fell, but the service changed its reminder texts at the same time. New injury assessments remained in person.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Use the paragraph to answer each conclusion.",
    yesNoStatements: [
      { id: "new-video", text: "New injury assessments were done by video.", answer: "No" },
      { id: "travel-costs-may", text: "Video follow-ups may have reduced travel-related costs.", answer: "Yes" },
      { id: "missed-definite", text: "The fall in missed appointments was definitely caused by video follow-ups.", answer: "No" },
      { id: "some-in-person", text: "Some patients still needed in-person appointments.", answer: "Yes" },
      { id: "over-twenty", text: "Travel reimbursements fell by more than 20%.", answer: "No" },
    ],
    explanation:
      "Video follow-ups were for patients not needing hands-on assessment, while new injuries stayed in person. Travel reimbursements fell by 18%, and causation for missed appointments is not proven because reminders changed too.",
  },
  {
    id: "dm-bank-yes-no-004",
    section: "dm",
    subtype: "dm-yes-no",
    tags: ["easy", "quick", "text-stem"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "Street trees in Milltown are planted to cool pavements, absorb some rainwater and improve air quality. Young trees need watering during dry spells and are more likely to survive if residents report damaged guards. The council says planting helps biodiversity, but it does not remove the need to cut traffic pollution.",
    ],
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Use the paragraph to answer each conclusion.",
    yesNoStatements: [
      { id: "cool-pavements", text: "Street trees can help cool pavements.", answer: "Yes" },
      { id: "guards-survival", text: "Reporting damaged guards may improve young tree survival.", answer: "Yes" },
      { id: "traffic-unneeded", text: "Planting trees removes the need to cut traffic pollution.", answer: "No" },
      { id: "all-survive", text: "All young trees survive dry spells without help.", answer: "No" },
      { id: "appearance-only", text: "The council only plants trees for appearance.", answer: "No" },
    ],
    explanation:
      "The paragraph lists cooling, rainwater absorption, air quality and biodiversity as purposes. It also says young trees need watering during dry spells and traffic pollution still needs reducing.",
  },
  {
    id: "dm-bank-yes-no-005",
    section: "dm",
    subtype: "dm-yes-no",
    tags: ["easy", "time-consuming", "multi-step", "data-display"],
    questionType: "yes-no",
    title: "Decision Making Practice",
    leftTitle: "Data",
    stimulus: [
      "The table shows the percentage by volume of particle sizes in four soil samples.",
    ],
    visual: {
      type: "table",
      title: "Soil sample composition",
      headers: ["Sample", "Gravel", "Sand", "Silt", "Clay"],
      rows: [
        ["A", "5%", "75%", "15%", "5%"],
        ["B", "20%", "30%", "25%", "25%"],
        ["C", "0%", "10%", "55%", "35%"],
        ["D", "70%", "20%", "5%", "5%"],
      ],
    },
    question:
      "Place 'Yes' if the conclusion follows. Place 'No' if the conclusion does not follow.",
    instruction: "Use the table to answer each conclusion.",
    yesNoStatements: [
      { id: "c-more-silt", text: "Sample C has more silt than clay.", answer: "Yes" },
      { id: "a-mostly-sand", text: "Sample A is mostly sand.", answer: "Yes" },
      { id: "b-d-same-clay", text: "Samples B and D have the same percentage of clay.", answer: "No" },
      { id: "silt-bc", text: "The silt percentages in Samples B and C total 80%.", answer: "Yes" },
      { id: "d-less-gravel-a", text: "Sample D has less gravel than Sample A.", answer: "No" },
    ],
    explanation:
      "Sample C has 55% silt and 35% clay. Sample A is 75% sand. B and D have 25% and 5% clay respectively. B and C silt totals 25% + 55% = 80%.",
  },
  {
    id: "dm-bank-venn-diagram-choice-001",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A revision programme surveyed 60 students about the resources they had used in the last month.",
      "34 students used online lessons, 29 used printed notes and 25 used question banks. Six students used all three resources. Nine used online lessons and printed notes only, seven used online lessons and question banks only, and five used printed notes and question banks only.",
    ],
    question:
      "If the pentagon, circle and triangle represent online lessons, printed notes and question banks respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Online lessons", "Printed notes", "Question banks"], {
          firstOnly: 12,
          secondOnly: 9,
          thirdOnly: 7,
          firstSecond: 9,
          firstThird: 5,
          secondThird: 7,
          allThree: 6,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Online lessons", "Printed notes", "Question banks"], {
          firstOnly: 12,
          secondOnly: 9,
          thirdOnly: 7,
          firstSecond: 9,
          firstThird: 7,
          secondThird: 5,
          allThree: 6,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Online lessons", "Printed notes", "Question banks"], {
          firstOnly: 13,
          secondOnly: 9,
          thirdOnly: 7,
          firstSecond: 9,
          firstThird: 7,
          secondThird: 5,
          allThree: 5,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Online lessons", "Printed notes", "Question banks"], {
          firstOnly: 7,
          secondOnly: 9,
          thirdOnly: 12,
          firstSecond: 9,
          firstThird: 7,
          secondThird: 5,
          allThree: 6,
        }),
      },
    ],
    answer: "B",
    explanation:
      "Online only = 34 - 9 - 7 - 6 = 12. Printed notes only = 29 - 9 - 5 - 6 = 9. Question banks only = 25 - 7 - 5 - 6 = 7. Diagram B places these values and the three overlaps correctly.",
  },
  {
    id: "dm-bank-venn-diagram-choice-002",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A clinic admin team surveyed 72 patients about the routes they had used to contact the clinic during a month.",
      "38 patients used the appointment app, 31 used the phone line and 26 used email. Four patients used all three routes. Eleven used the app and phone line only, twelve used the app and email only, and six used the phone line and email only.",
    ],
    question:
      "If the pentagon, circle and triangle represent the appointment app, phone line and email respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Appointment app", "Phone line", "Email"], {
          firstOnly: 11,
          secondOnly: 10,
          thirdOnly: 4,
          firstSecond: 12,
          firstThird: 11,
          secondThird: 6,
          allThree: 4,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Appointment app", "Phone line", "Email"], {
          firstOnly: 12,
          secondOnly: 10,
          thirdOnly: 3,
          firstSecond: 11,
          firstThird: 12,
          secondThird: 6,
          allThree: 4,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Appointment app", "Phone line", "Email"], {
          firstOnly: 11,
          secondOnly: 8,
          thirdOnly: 6,
          firstSecond: 11,
          firstThird: 12,
          secondThird: 6,
          allThree: 4,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Appointment app", "Phone line", "Email"], {
          firstOnly: 11,
          secondOnly: 10,
          thirdOnly: 4,
          firstSecond: 11,
          firstThird: 12,
          secondThird: 6,
          allThree: 4,
        }),
      },
    ],
    answer: "D",
    explanation:
      "App only = 38 - 11 - 12 - 4 = 11, phone only = 31 - 11 - 6 - 4 = 10, and email only = 26 - 12 - 6 - 4 = 4. Diagram D matches all three single regions and all overlaps.",
  },
  {
    id: "dm-bank-venn-diagram-choice-003",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A hospital education team recorded which training formats were completed by 80 staff members.",
      "45 staff completed live briefings, 38 completed e-learning and 35 completed simulation sessions. Ten completed all three formats. Eight completed live briefings and e-learning only, twelve completed live briefings and simulation only, and six completed e-learning and simulation only.",
    ],
    question:
      "If the pentagon, circle and triangle represent live briefings, e-learning and simulation sessions respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Live briefings", "E-learning", "Simulation"], {
          firstOnly: 15,
          secondOnly: 14,
          thirdOnly: 7,
          firstSecond: 8,
          firstThird: 12,
          secondThird: 6,
          allThree: 10,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Live briefings", "E-learning", "Simulation"], {
          firstOnly: 14,
          secondOnly: 15,
          thirdOnly: 7,
          firstSecond: 8,
          firstThird: 12,
          secondThird: 6,
          allThree: 10,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Live briefings", "E-learning", "Simulation"], {
          firstOnly: 15,
          secondOnly: 14,
          thirdOnly: 7,
          firstSecond: 12,
          firstThird: 8,
          secondThird: 6,
          allThree: 10,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Live briefings", "E-learning", "Simulation"], {
          firstOnly: 15,
          secondOnly: 14,
          thirdOnly: 9,
          firstSecond: 8,
          firstThird: 12,
          secondThird: 6,
          allThree: 8,
        }),
      },
    ],
    answer: "A",
    explanation:
      "Live-only = 45 - 8 - 12 - 10 = 15. E-learning only = 38 - 8 - 6 - 10 = 14. Simulation only = 35 - 12 - 6 - 10 = 7. Diagram A is the only option with all of these and the stated overlaps.",
  },
  {
    id: "dm-bank-venn-diagram-choice-004",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "An arts centre surveyed 68 visitors about materials they used during a visit.",
      "32 visitors used a gallery map, 30 used an audio guide and 27 used a workshop leaflet. Five visitors used all three. Eight used the gallery map and audio guide only, six used the gallery map and workshop leaflet only, and seven used the audio guide and workshop leaflet only.",
    ],
    question:
      "If the pentagon, circle and triangle represent the gallery map, audio guide and workshop leaflet respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Gallery map", "Audio guide", "Workshop leaflet"], {
          firstOnly: 13,
          secondOnly: 10,
          thirdOnly: 9,
          firstSecond: 8,
          firstThird: 7,
          secondThird: 6,
          allThree: 5,
          neither: 10,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Gallery map", "Audio guide", "Workshop leaflet"], {
          firstOnly: 12,
          secondOnly: 10,
          thirdOnly: 9,
          firstSecond: 8,
          firstThird: 6,
          secondThird: 7,
          allThree: 6,
          neither: 10,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Gallery map", "Audio guide", "Workshop leaflet"], {
          firstOnly: 13,
          secondOnly: 10,
          thirdOnly: 9,
          firstSecond: 8,
          firstThird: 6,
          secondThird: 7,
          allThree: 5,
          neither: 10,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Gallery map", "Audio guide", "Workshop leaflet"], {
          firstOnly: 9,
          secondOnly: 10,
          thirdOnly: 13,
          firstSecond: 8,
          firstThird: 6,
          secondThird: 7,
          allThree: 5,
          neither: 10,
        }),
      },
    ],
    answer: "C",
    explanation:
      "Map only = 32 - 8 - 6 - 5 = 13. Audio only = 30 - 8 - 7 - 5 = 10. Leaflet only = 27 - 6 - 7 - 5 = 9. Diagram C also leaves 10 visitors outside all three categories.",
  },
  {
    id: "dm-bank-venn-diagram-choice-005",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A practice group of 74 students recorded which revision supports they used in one week.",
      "35 students used mock review, 30 used a formula sheet and 28 used calculator drills. Four students used all three. Nine used mock review and the formula sheet only, eight used mock review and calculator drills only, and six used the formula sheet and calculator drills only.",
    ],
    question:
      "If the pentagon, circle and triangle represent mock review, formula sheet and calculator drills respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Mock review", "Formula sheet", "Calculator drills"], {
          firstOnly: 14,
          secondOnly: 11,
          thirdOnly: 10,
          firstSecond: 8,
          firstThird: 9,
          secondThird: 6,
          allThree: 4,
          neither: 12,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Mock review", "Formula sheet", "Calculator drills"], {
          firstOnly: 15,
          secondOnly: 10,
          thirdOnly: 10,
          firstSecond: 9,
          firstThird: 8,
          secondThird: 6,
          allThree: 4,
          neither: 12,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Mock review", "Formula sheet", "Calculator drills"], {
          firstOnly: 14,
          secondOnly: 11,
          thirdOnly: 10,
          firstSecond: 9,
          firstThird: 8,
          secondThird: 4,
          allThree: 6,
          neither: 12,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Mock review", "Formula sheet", "Calculator drills"], {
          firstOnly: 14,
          secondOnly: 11,
          thirdOnly: 10,
          firstSecond: 9,
          firstThird: 8,
          secondThird: 6,
          allThree: 4,
          neither: 12,
        }),
      },
    ],
    answer: "D",
    explanation:
      "Mock-only = 35 - 9 - 8 - 4 = 14, formula-only = 30 - 9 - 6 - 4 = 11, and calculator-only = 28 - 8 - 6 - 4 = 10. The union is 62, so 12 students used none of the three supports. Diagram D matches.",
  },
  {
    id: "dm-bank-venn-diagram-choice-006",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "An admissions workshop recorded which experiences were reported by 70 applicants.",
      "30 applicants reported volunteering, 31 reported research experience and 33 reported attending an open day. Five applicants reported all three. Six reported volunteering and research only, nine reported volunteering and an open day only, and eight reported research and an open day only.",
    ],
    question:
      "If the pentagon, circle and triangle represent volunteering, research and open day respectively, which diagram best represents the data?",
    options: [
      {
        key: "A",
        text: "Diagram A",
        visual: threeSetDiagram("Diagram A", ["Volunteering", "Research", "Open day"], {
          firstOnly: 10,
          secondOnly: 12,
          thirdOnly: 11,
          firstSecond: 9,
          firstThird: 6,
          secondThird: 8,
          allThree: 5,
          neither: 9,
        }),
      },
      {
        key: "B",
        text: "Diagram B",
        visual: threeSetDiagram("Diagram B", ["Volunteering", "Research", "Open day"], {
          firstOnly: 10,
          secondOnly: 12,
          thirdOnly: 11,
          firstSecond: 6,
          firstThird: 9,
          secondThird: 8,
          allThree: 5,
          neither: 9,
        }),
      },
      {
        key: "C",
        text: "Diagram C",
        visual: threeSetDiagram("Diagram C", ["Volunteering", "Research", "Open day"], {
          firstOnly: 11,
          secondOnly: 12,
          thirdOnly: 10,
          firstSecond: 6,
          firstThird: 9,
          secondThird: 8,
          allThree: 5,
          neither: 9,
        }),
      },
      {
        key: "D",
        text: "Diagram D",
        visual: threeSetDiagram("Diagram D", ["Volunteering", "Research", "Open day"], {
          firstOnly: 10,
          secondOnly: 12,
          thirdOnly: 11,
          firstSecond: 6,
          firstThird: 9,
          secondThird: 5,
          allThree: 8,
          neither: 9,
        }),
      },
    ],
    answer: "B",
    explanation:
      "Volunteering only = 30 - 6 - 9 - 5 = 10, research only = 31 - 6 - 8 - 5 = 12, and open-day only = 33 - 9 - 8 - 5 = 11. These exact regions, plus 9 outside all three, match Diagram B.",
  },
  {
    id: "dm-bank-venn-001",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["easy", "quick", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "A library recorded which members borrowed fiction books, non-fiction books and audiobooks. Each number shows members in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Borrowing choices",
      shapes: [
        { id: "fiction", label: "Fiction", shape: "circle", x: 70, y: 95, width: 250, height: 230 },
        { id: "nonfiction", label: "Non-fiction", shape: "rectangle", x: 225, y: 140, width: 280, height: 180 },
        { id: "audio", label: "Audiobooks", shape: "triangle", x: 150, y: 55, width: 330, height: 300 },
      ],
      regionLabels: [
        { id: "fiction-only", text: "18", x: 135, y: 225 },
        { id: "nonfiction-only", text: "20", x: 455, y: 245 },
        { id: "audio-only", text: "9", x: 315, y: 105 },
        { id: "fiction-nonfiction", text: "12", x: 235, y: 155 },
        { id: "fiction-audio", text: "7", x: 220, y: 230 },
        { id: "nonfiction-audio", text: "10", x: 380, y: 190 },
        { id: "all-three", text: "5", x: 275, y: 220 },
      ],
      legend: [
        { label: "Fiction", shape: "circle" },
        { label: "Non-fiction", shape: "rectangle" },
        { label: "Audiobooks", shape: "triangle" },
      ],
    },
    question:
      "How many members borrowed fiction and non-fiction books but not audiobooks?",
    options: [
      { key: "A", text: "5" },
      { key: "B", text: "12" },
      { key: "C", text: "17" },
      { key: "D", text: "24" },
    ],
    answer: "B",
    explanation:
      "The exact overlap between fiction and non-fiction, outside audiobooks, is labelled 12.",
  },
  {
    id: "dm-bank-venn-002",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "A training centre recorded applicants with communication, teamwork, problem-solving and organisation experience. Each number shows applicants in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Applicant qualities",
      shapes: [
        { id: "communication", label: "Communication", shape: "circle", x: 70, y: 100, width: 230, height: 210 },
        { id: "teamwork", label: "Teamwork", shape: "rectangle", x: 205, y: 80, width: 250, height: 210 },
        { id: "problem", label: "Problem-solving", shape: "diamond", x: 180, y: 125, width: 260, height: 230 },
        { id: "organisation", label: "Organisation", shape: "triangle", x: 285, y: 40, width: 270, height: 300 },
      ],
      regionLabels: [
        { id: "comm-only", text: "14", x: 125, y: 205 },
        { id: "team-only", text: "11", x: 385, y: 120 },
        { id: "problem-only", text: "9", x: 245, y: 315 },
        { id: "org-only", text: "8", x: 470, y: 95 },
        { id: "comm-team", text: "7", x: 245, y: 155 },
        { id: "team-problem", text: "5", x: 350, y: 245 },
        { id: "problem-org", text: "6", x: 405, y: 275 },
        { id: "comm-org", text: "4", x: 295, y: 125 },
        { id: "comm-team-problem", text: "10", x: 275, y: 215 },
        { id: "team-problem-org", text: "12", x: 385, y: 200 },
        { id: "all-four", text: "3", x: 330, y: 185 },
      ],
      legend: [
        { label: "Communication", shape: "circle" },
        { label: "Teamwork", shape: "rectangle" },
        { label: "Problem-solving", shape: "diamond" },
        { label: "Organisation", shape: "triangle" },
      ],
    },
    question: "How many applicants have at least three of the qualities?",
    options: [
      { key: "A", text: "15" },
      { key: "B", text: "22" },
      { key: "C", text: "25" },
      { key: "D", text: "47" },
    ],
    answer: "C",
    explanation:
      "At least three qualities includes 10, 12 and 3, giving 25 applicants.",
  },
  {
    id: "dm-bank-venn-003",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "Students joined one or more enrichment clubs: coding, art, music and drama. Each number shows students in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Enrichment clubs",
      shapes: [
        { id: "coding", label: "Coding", shape: "rectangle", x: 55, y: 70, width: 275, height: 165 },
        { id: "art", label: "Art", shape: "hexagon", x: 235, y: 50, width: 270, height: 230 },
        { id: "music", label: "Music", shape: "circle", x: 90, y: 125, width: 250, height: 225 },
        { id: "drama", label: "Drama", shape: "triangle", x: 205, y: 120, width: 290, height: 285 },
      ],
      regionLabels: [
        { id: "coding-only", text: "10", x: 95, y: 125 },
        { id: "art-only", text: "13", x: 440, y: 150 },
        { id: "music-only", text: "15", x: 145, y: 270 },
        { id: "drama-only", text: "11", x: 330, y: 355 },
        { id: "coding-art", text: "6", x: 285, y: 130 },
        { id: "coding-music", text: "8", x: 185, y: 180 },
        { id: "art-music", text: "4", x: 265, y: 220 },
        { id: "art-drama", text: "7", x: 390, y: 245 },
        { id: "music-drama", text: "5", x: 245, y: 300 },
        { id: "coding-music-drama", text: "3", x: 230, y: 235 },
        { id: "art-music-drama", text: "2", x: 315, y: 255 },
        { id: "all-four", text: "1", x: 285, y: 205 },
      ],
      legend: [
        { label: "Coding", shape: "rectangle" },
        { label: "Art", shape: "hexagon" },
        { label: "Music", shape: "circle" },
        { label: "Drama", shape: "triangle" },
      ],
    },
    question: "How many students joined exactly two of the clubs?",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "25" },
      { key: "C", text: "30" },
      { key: "D", text: "33" },
    ],
    answer: "C",
    explanation:
      "Exactly two clubs are represented by 6, 8, 4, 7 and 5. These total 30.",
  },
  {
    id: "dm-bank-venn-004",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "A community centre recorded young people taking part in robotics, choir, gardening and journalism clubs. Each number shows young people in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Community centre clubs",
      shapes: [
        { id: "robotics", label: "Robotics", shape: "circle", x: 80, y: 85, width: 265, height: 230 },
        { id: "choir", label: "Choir", shape: "rectangle", x: 215, y: 105, width: 285, height: 180 },
        { id: "gardening", label: "Gardening", shape: "triangle", x: 145, y: 45, width: 295, height: 300 },
        { id: "journalism", label: "Journalism", shape: "hexagon", x: 255, y: 175, width: 270, height: 180 },
      ],
      regionLabels: [
        { id: "robotics-only", text: "21", x: 145, y: 200 },
        { id: "choir-only", text: "17", x: 455, y: 155 },
        { id: "gardening-only", text: "14", x: 270, y: 95 },
        { id: "journalism-only", text: "12", x: 460, y: 295 },
        { id: "robotics-choir", text: "10", x: 275, y: 200 },
        { id: "robotics-gardening", text: "6", x: 235, y: 140 },
        { id: "robotics-journalism", text: "8", x: 260, y: 285 },
        { id: "choir-gardening", text: "9", x: 360, y: 145 },
        { id: "choir-journalism", text: "5", x: 410, y: 245 },
        { id: "robotics-choir-gardening", text: "11", x: 305, y: 165 },
        { id: "robotics-choir-journalism", text: "7", x: 330, y: 245 },
        { id: "robotics-gardening-journalism", text: "4", x: 295, y: 215 },
        { id: "all-four", text: "3", x: 350, y: 205 },
      ],
      legend: [
        { label: "Robotics", shape: "circle" },
        { label: "Choir", shape: "rectangle" },
        { label: "Gardening", shape: "triangle" },
        { label: "Journalism", shape: "hexagon" },
      ],
    },
    question: "How many young people do robotics and exactly two other clubs?",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "22" },
      { key: "C", text: "25" },
      { key: "D", text: "28" },
    ],
    answer: "B",
    explanation:
      "Robotics plus exactly two other clubs means the three-club regions that include robotics: 11, 7 and 4. The all-four region is not included. The total is 22.",
  },
  {
    id: "dm-bank-venn-005",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["hard", "time-consuming", "multi-step", "set-based", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Information",
    stimulus: [
      "A clothing shop records three features of its jackets: black colour, waterproof fabric and reflective strips. Every jacket has at least one of these features, and every jacket is either black or grey.",
      "18 jackets are only black. 30 jackets have all three features. 45 jackets have exactly two of the features, divided equally between the three possible two-feature combinations. 22 jackets are only waterproof. 26 jackets are only reflective.",
    ],
    question: "How many jackets are grey?",
    options: [
      { key: "A", text: "58" },
      { key: "B", text: "63" },
      { key: "C", text: "78" },
      { key: "D", text: "96" },
    ],
    answer: "B",
    explanation:
      "Grey jackets are those without the black feature: only waterproof (22), only reflective (26), and waterproof plus reflective only (15). This gives 63.",
  },
  {
    id: "dm-bank-venn-006",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["hard", "time-consuming", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "The diagram shows patients receiving physiotherapy, dietetic advice, blood tests and medication review during a clinic day. Each number shows patients in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Clinic services",
      shapes: [
        { id: "physio", label: "Physiotherapy", shape: "circle", x: 70, y: 90, width: 250, height: 220 },
        { id: "diet", label: "Dietetic advice", shape: "rectangle", x: 190, y: 85, width: 280, height: 210 },
        { id: "bloods", label: "Blood tests", shape: "triangle", x: 260, y: 45, width: 280, height: 300 },
        { id: "meds", label: "Medication review", shape: "hexagon", x: 115, y: 185, width: 300, height: 170 },
      ],
      regionLabels: [
        { id: "physio-only", text: "20", x: 120, y: 185 },
        { id: "diet-only", text: "22", x: 425, y: 165 },
        { id: "bloods-only", text: "16", x: 430, y: 95 },
        { id: "meds-only", text: "18", x: 210, y: 325 },
        { id: "physio-diet", text: "5", x: 245, y: 155 },
        { id: "physio-meds", text: "7", x: 205, y: 255 },
        { id: "diet-bloods", text: "9", x: 375, y: 155 },
        { id: "diet-meds", text: "6", x: 330, y: 260 },
        { id: "physio-diet-meds", text: "4", x: 270, y: 220 },
        { id: "diet-bloods-meds", text: "3", x: 365, y: 225 },
        { id: "all-four", text: "2", x: 315, y: 195 },
      ],
      legend: [
        { label: "Physiotherapy", shape: "circle" },
        { label: "Dietetic advice", shape: "rectangle" },
        { label: "Blood tests", shape: "triangle" },
        { label: "Medication review", shape: "hexagon" },
      ],
    },
    question: "How many patients received more than one service?",
    options: [
      { key: "A", text: "28" },
      { key: "B", text: "36" },
      { key: "C", text: "40" },
      { key: "D", text: "72" },
    ],
    answer: "B",
    explanation:
      "More than one service includes all overlap regions: 5 + 7 + 9 + 6 + 4 + 3 + 2 = 36.",
  },
  {
    id: "dm-bank-venn-007",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "A school recorded students with North, East, South and West family heritage. Each number shows students in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Student heritage",
      shapes: [
        { id: "north", label: "North", shape: "hexagon", x: 50, y: 95, width: 250, height: 205 },
        { id: "east", label: "East", shape: "circle", x: 155, y: 60, width: 275, height: 240 },
        { id: "south", label: "South", shape: "triangle", x: 300, y: 90, width: 285, height: 290 },
        { id: "west", label: "West", shape: "diamond", x: 180, y: 185, width: 270, height: 200 },
      ],
      regionLabels: [
        { id: "north-only", text: "30", x: 95, y: 185 },
        { id: "east-only", text: "45", x: 290, y: 105 },
        { id: "south-only", text: "25", x: 485, y: 270 },
        { id: "west-only", text: "20", x: 270, y: 350 },
        { id: "north-east", text: "12", x: 210, y: 155 },
        { id: "east-south", text: "10", x: 385, y: 170 },
        { id: "south-west", text: "8", x: 370, y: 300 },
        { id: "north-west", text: "6", x: 205, y: 255 },
        { id: "north-east-south", text: "9", x: 320, y: 185 },
        { id: "east-south-west", text: "5", x: 350, y: 245 },
        { id: "all-four", text: "3", x: 295, y: 225 },
      ],
      legend: [
        { label: "North", shape: "hexagon" },
        { label: "East", shape: "circle" },
        { label: "South", shape: "triangle" },
        { label: "West", shape: "diamond" },
      ],
    },
    question: "Which of the following statements is correct?",
    options: [
      { key: "A", text: "More than 50% of the students have East heritage." },
      { key: "B", text: "Less than 20% of students have more than one heritage." },
      { key: "C", text: "More than 5% of the students have exactly two heritages." },
      { key: "D", text: "Exactly 30% of students have North or South heritage." },
    ],
    answer: "C",
    explanation:
      "The total is 173. Exactly two heritages total 12 + 10 + 8 + 6 = 36, which is more than 5% of 173. The other percentage claims are not correct.",
  },
  {
    id: "dm-bank-venn-008",
    section: "dm",
    subtype: "dm-venn-sets",
    tags: ["medium", "multi-step", "set-based", "data-display"],
    title: "Decision Making Practice",
    leftTitle: "Diagram",
    stimulus: [
      "A craft fair recorded bracelets made with jade, opal and pearl. Each number shows bracelets in that exact region.",
    ],
    visual: {
      type: "set-diagram",
      title: "Bracelet materials",
      shapes: [
        { id: "jade", label: "Jade", shape: "circle", x: 80, y: 95, width: 230, height: 210 },
        { id: "opal", label: "Opal", shape: "rectangle", x: 230, y: 110, width: 260, height: 180 },
        { id: "pearl", label: "Pearl", shape: "triangle", x: 190, y: 45, width: 285, height: 285 },
      ],
      regionLabels: [
        { id: "jade-only", text: "19", x: 145, y: 215 },
        { id: "opal-only", text: "21", x: 430, y: 215 },
        { id: "pearl-only", text: "17", x: 335, y: 95 },
        { id: "jade-opal", text: "12", x: 270, y: 225 },
        { id: "jade-pearl", text: "8", x: 245, y: 160 },
        { id: "opal-pearl", text: "10", x: 385, y: 165 },
        { id: "all-three", text: "6", x: 315, y: 195 },
      ],
      legend: [
        { label: "Jade", shape: "circle" },
        { label: "Opal", shape: "rectangle" },
        { label: "Pearl", shape: "triangle" },
      ],
    },
    question:
      "How many bracelets feature exactly two materials?",
    options: [
      { key: "A", text: "18" },
      { key: "B", text: "30" },
      { key: "C", text: "36" },
      { key: "D", text: "42" },
    ],
    answer: "B",
    explanation:
      "Exactly two materials are jade and opal (12), jade and pearl (8), and opal and pearl (10). These total 30.",
  },
  {
    id: "dm-bank-probability-001",
    section: "dm",
    subtype: "dm-probability-data",
    tags: ["easy", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Probability",
    stimulus: [
      "Two bakeries make the same number of pastries each morning. At Bakery A, 85% of pastries pass the bake check, and 20% of those that pass are later rejected for packaging faults. At Bakery B, 80% pass the bake check, and 10% of those that pass are later rejected for packaging faults.",
    ],
    question:
      "Considering only these two checks, does Bakery A have more pastries that are ready for sale?",
    options: [
      { key: "A", text: "Yes, because Bakery A has the higher bake-check pass rate." },
      { key: "B", text: "Yes, because Bakery B rejects more pastries overall." },
      { key: "C", text: "No, because Bakery B has the higher expected ready-for-sale proportion." },
      { key: "D", text: "No, because both bakeries have the same expected ready-for-sale proportion." },
    ],
    answer: "C",
    explanation:
      "Bakery A has 0.85 x 0.80 = 0.68 ready for sale. Bakery B has 0.80 x 0.90 = 0.72 ready for sale, so Bakery B is higher.",
  },
  {
    id: "dm-bank-probability-002",
    section: "dm",
    subtype: "dm-probability-data",
    tags: ["easy", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Probability",
    stimulus: [
      "A game uses a bag that initially contains 40 blue counters and 40 green counters. Counters are not replaced. A player wins on their current turn if they pick five blue counters in a row. They have already picked two blue counters this turn. Across the game so far, including those two counters, 10 blue counters and 8 green counters have been taken out.",
    ],
    question:
      "The player thinks their chance of winning on this turn is between 10% and 11%. Is the player correct?",
    options: [
      { key: "A", text: "Yes, because 30/62 x 29/61 x 28/60 is between 10% and 11%." },
      { key: "B", text: "Yes, because having two blue counters already guarantees the next three are blue." },
      { key: "C", text: "No, because the chance is over 11%." },
      { key: "D", text: "No, because the chance is less than 10%." },
    ],
    answer: "A",
    explanation:
      "After 10 blue and 8 green counters are removed, 30 blue and 32 green remain. The chance of three more blues is 30/62 x 29/61 x 28/60, about 10.7%.",
  },
  {
    id: "dm-bank-probability-003",
    section: "dm",
    subtype: "dm-probability-data",
    tags: ["easy", "quick", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Probability",
    stimulus: [
      "Team Alpha and Team Beta are two emergency response teams. Team Alpha reaches a call in an average of 36 seconds and successfully resolves the case in 9% of calls. Team Beta reaches a call in an average of three-fifths of a minute and fails to resolve the case in 92% of calls.",
    ],
    question:
      "Giving equal consideration to response time and success rate, which team is more effective?",
    options: [
      { key: "A", text: "Team Alpha, because its response time is shorter and its success rate is lower." },
      { key: "B", text: "Team Alpha, because its success rate is higher and its response time is the same." },
      { key: "C", text: "Team Beta, because its success rate is higher and its response time is shorter." },
      { key: "D", text: "Team Beta, because both teams have the same success rate." },
    ],
    answer: "B",
    explanation:
      "Three-fifths of a minute is 36 seconds. Team Beta fails in 92% of calls, so succeeds in 8%. Team Alpha has the same response time and a higher success rate.",
  },
  {
    id: "dm-bank-probability-004",
    section: "dm",
    subtype: "dm-probability-data",
    tags: ["easy", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Probability",
    stimulus: [
      "Meghan is choosing between Phone A and Phone B. Phone A has a 70% chance of being damaged after being submerged in water for 6 minutes. Phone B has a 25% chance of being damaged after being submerged in water for 6 minutes. Phone A processes 3 billion instructions every 4 seconds. Phone B processes 6 billion instructions every 8 seconds.",
    ],
    question:
      "Considering only water damage chance and processing speed, is Phone A the better choice?",
    options: [
      { key: "A", text: "Yes, because Phone A has a lower chance of water damage." },
      { key: "B", text: "Yes, because Phone A has a faster processing speed." },
      { key: "C", text: "No, because Phone B has a lower chance of water damage and the same processing speed." },
      { key: "D", text: "No, because Phone B has a higher chance of water damage and a slower processing speed." },
    ],
    answer: "C",
    explanation:
      "Both phones process 0.75 billion instructions per second. Phone B has the lower damage chance, so Phone A is not better on these factors.",
  },
  {
    id: "dm-bank-probability-005",
    section: "dm",
    subtype: "dm-probability-data",
    tags: ["easy", "multi-step", "text-stem"],
    title: "Decision Making Practice",
    leftTitle: "Probability",
    stimulus: [
      "A company is comparing two marketing strategies. Strategy A is expected to reach 4% of the target audience every 5 days, while Strategy B is expected to reach 10% every 20 days. Strategy A is projected to appeal to 42 out of every 50 potential customers reached, while Strategy B is projected to appeal to 72 out of every 100 potential customers reached.",
    ],
    question:
      "Considering only reach rate and appeal rate, should the company choose Strategy B?",
    options: [
      { key: "A", text: "Yes, because Strategy B reaches people faster and appeals to a higher proportion." },
      { key: "B", text: "Yes, because Strategy B appeals to 72 people." },
      { key: "C", text: "No, because the two strategies have the same reach rate and appeal rate." },
      { key: "D", text: "No, because Strategy A has both the higher reach rate and the higher appeal rate." },
    ],
    answer: "D",
    explanation:
      "Strategy A reaches 0.8% per day, while Strategy B reaches 0.5% per day. Strategy A appeals to 84% of those reached, while Strategy B appeals to 72%.",
  },
];
