// Transcribed from the final, visually inspected PNGs. Candidate-facing facts
// only: calculations, interpretation and marking points live in the markscheme.
export type InterviewStimulus = {
  id: string;
  src: string;
  title: string;
  description: string;
};

const sources: Record<string, readonly [string, string]> = {
  "iq-18-001-data-stations": ["GP appointment waits across two districts", "Routine appointments, 2019–2024. Mean wait in days, in year order: North 6, 7, 11, 13, 12, 10; South 5, 6, 8, 9, 11, 12. Practices submitting data: North 18, 18, 17, 15, 15, 14; South 20, 20, 20, 21, 22, 22. North introduced online triage in January 2022; South in January 2024. Annual means use each year's reporting practices. Urgent appointments excluded. Patient age and appointment demand were not recorded. Fictional regional audit."],
  "iq-18-002-data-stations": ["Six-month smoking cessation programme results", "Service evaluation of three self-selected programmes. Columns: enrolled; followed up; reported quitting; still smoking; not followed up. Text support: 200; 150; 48; 102; 50. Group sessions: 120; 108; 43; 65; 12. One-to-one support: 80; 60; 30; 30; 20. Mean age, median cigarettes/day at entry and total cost: text 29, 12, £8,000; group 46, 18, £18,000; one-to-one 52, 22, £24,000. Participants chose their programme. Quitting was self-reported at six months, without biochemical confirmation. Quitters and still-smoking counts refer only to those followed up. Missing outcomes are unknown. Fictional data."],
  "iq-18-003-data-stations": ["Weekly exercise and reported wellbeing", "Cross-sectional online survey of 240 adults. Exercise groups: less than 1 hour, 1–3 hours, 4–6 hours, more than 6 hours weekly. Mean wellbeing scores out of 10 (95% confidence interval; sample size), in group order. Ages 18–39: 5.4 (4.9–5.9; 30), 6.2 (5.8–6.6; 45), 7.1 (6.7–7.5; 30), 6.9 (6.0–7.8; 15). Ages 40–65: 4.9 (4.4–5.4; 35), 5.8 (5.4–6.2; 40), 6.5 (6.0–7.0; 30), 6.7 (5.7–7.7; 15). The chart shows means; intervals are in the table. Exercise and wellbeing were self-reported. Income, health conditions and sleep were not recorded. Fictional data."],
  "iq-18-004-data-stations": ["Options for a community diabetes programme", "First-year budget £200,000; funding for one programme. Columns: annual invitations, expected attendance, annual running cost, one-off setup cost. Mobile clinic: 1,200, 68%, £180,000, £35,000. Evening clinic: 800, 81%, £120,000, £15,000. Online support: 2,400, 42%, £90,000, £45,000. Mobile launches in 5 months and needs two nurses for weekly rural visits. Evening launches in 2 months with one nurse at a town-centre site. Online launches in 3 months and requires internet access and a remote educator. Budget covers setup and running costs; no extra funding confirmed. Attendance estimates come from small pilots in different areas. An estimated 18% of the local target population lacks reliable internet. Health outcomes, long-term retention and adverse effects were not measured. Fictional planning data."],
  "iq-18-005-data-stations": ["Ward admissions and discharge delays", "Twenty sampled ward-days across two wards. Scatterplot: daily admissions on x-axis; mean time from discharge decision to leaving in hours on y-axis. Approximate plotted pairs for Ward A: (12,2.1), (16,2.8), (20,2.4), (24,3.3), (28,3.0), (32,3.8), (36,3.4), (40,4.4), (44,4.0), (48,4.8). Ward B: (14,2.8), (18,3.5), (22,3.1), (24,7.5), (26,4.0), (30,3.6), (34,4.5), (38,4.0), (42,5.0), (46,4.6). Ward A has 28 beds, median nurse-to-patient ratio 1:6, and 2 of 10 sampled days at weekends. Ward B has 36 beds, ratio 1:8, and 4 of 10 days at weekends. Sampling covered six weeks. Patient complexity and transport availability were not recorded. Fictional audit."],
  "iq-18-006-graphs-and-trends": ["Patient satisfaction briefing", "Hospital communications headline: Patient satisfaction rises sharply. 2024 inpatient survey bar chart: Hospital A 82%, Hospital B 86%; vertical axis runs from 80% to 87%. Measure: overall satisfaction with inpatient care. Hospital A: 2,000 invitations, 500 responses, 410 answered yes; anonymous postal form, January–March. Hospital B: 1,000 invitations, 100 responses, 86 answered yes; interview with ward staff, October–December. Respondents were adults discharged from inpatient wards. Patient age, illness severity and previous-year results were not provided. Fictional communications extract."],
  "iq-18-007-graphs-and-trends": ["Childhood vaccination uptake", "Completed scheduled vaccinations by age two, 2018–2024. Percent eligible children vaccinated in year order: North 93, 92, 89, 86, 87, 89, 91; South 94, 93, 91, 90, 90, 92, 93. Eligible children recorded: North 1,000, 1,000, 1,100, 1,200, 1,300, 1,400, 1,500; South 1,500, 1,500, 1,600, 1,600, 1,700, 1,700, 1,800. In 2021 both districts updated child-registration records. In 2022 North introduced reminder texts. In 2023 both added weekend clinics. Uptake uses each year's registered eligible population. Migration and individual reasons for missed vaccination were not recorded. Fictional audit."],
  "iq-18-008-graphs-and-trends": ["Average nightly sleep and exam score", "Survey of 40 students sitting the same exam; 40 of 120 invited responded. Scatterplot x-axis self-reported sleep 4–10 hours/night, y-axis exam score 40–100%. Twenty students per revision group. Approximate under-10-hours/week pairs: (4.3,46), (4.6,60), (4.9,51), (5.2,65), (5.5,49), (5.8,68), (6.1,56), (6.4,72), (6.6,45), (6.7,59), (7.0,76), (7.3,62), (7.6,71), (7.9,65), (8.2,80), (8.5,68), (8.8,74), (9.1,70), (9.4,83), (9.7,73). Approximate 10-plus-hours/week pairs: (4.4,58), (4.7,72), (5.0,61), (5.3,77), (5.6,64), (5.9,80), (6.2,67), (6.5,83), (6.8,69), (7.1,86), (7.4,73), (7.7,90), (7.85,58), (8.0,76), (8.3,88), (8.6,79), (8.9,93), (9.2,82), (9.5,89), (9.8,85). Sleep and revision were recalled after the exam. Prior attainment, stress, health and caffeine were not recorded. Fictional student survey."],
  "iq-18-009-data-interpretation": ["Chance of another heart event within five years", "Fictional randomised treatment study with 1,000 adults per group and complete five-year outcomes. Standard care: 20 in 100 had another heart event; 3 in 100 had major bleeding; no extra tablets or visits. Standard care plus new treatment: 15 in 100 had another heart event; 6 in 100 had major bleeding; one extra daily tablet; two extra monitoring visits per year. Each chart icon represents 1 in 100 people. Heart events and major bleeding may affect the same person. Individual risks may differ."],
  "iq-18-010-data-interpretation": ["Recovery after two physiotherapy programmes", "200 adults randomly assigned, 100 per programme. At 12 weeks, categories much better / a little better / no better or worse / did not respond: A 54 / 26 / 15 / 5; B 62 / 23 / 10 / 5. At six months: A 50 / 20 / 18 / 12; B 52 / 18 / 12 / 18. All counts use the original 100 per group. A has 4 supervised sessions, typical 20-minute travel per session, 10 in 100 reporting a temporary pain flare. B has 8 sessions, 50-minute travel, 18 in 100 reporting a flare. Missing outcomes unknown. Recovery self-reported; participants knew their programme. Both received home exercises. No follow-up beyond six months. Fictional study."],
  "iq-18-011-critical-appraisal": ["Energy drinks and concentration", "60 volunteers aged 18–30 recruited via the maker's social media chose an energy drink or water. One-hour test, no blinding. Drink/water: enrolled 36/24; completed both tests 33/21; mean score before out of 100 48/49; after 54/50; regular caffeine users 24/33 and 8/21. Scores are for completers. Report states the drink group scored 8% higher than water after one hour. Company-funded. Sleep and other caffeine unrecorded. Fictional study."],
  "iq-18-012-critical-appraisal": ["Reminder texts and missed appointments", "24 adults, random allocation, one clinic, four weeks. Extra text: 2/12 missed an appointment, 10 attended. Usual care: 4/12 missed, 8 attended. Two texts were undelivered; participants analysed as assigned. £0.08 per text, staff costs unrecorded. Report says difference not statistically significant. No sample-size calculation or confidence interval. Phone owners only, one appointment each, complete follow-up. Fictional pilot study."],
  "iq-18-013-article-analysis": ["Asthma app: eight-week evaluation", "Single hospital: 80 started, 50 completed, 30 missing. Missing reasons: 10 technical problems, 6 reporting burden, 14 unknown. Means for 50 completers, before / eight weeks: symptoms out of 10 6.2 / 4.1; missed-activity days per month 3 / 2; reliever-use days per week 4 / 3. Higher symptom score means more symptoms. No comparison group. Medication changed in 18/50 completers. Developer-funded. Questionnaire validation not described. Full questionnaire, protocol and raw data unpublished. Fictional evaluation."],
  "iq-18-014-article-analysis": ["Berry news and study", "Fictional news headline: Berry halves cancer risk. Subheading: Fewer diagnoses among berry eaters. Study: 600 adults, 18 months, observational. Berry eaters / others: participants 200 / 400; new diagnoses 12 / 20; mean age 54 / 61; current smokers 20% / 30%; higher-income households 75% / 40%. Diet self-reported once. Complete follow-up with clinical-record diagnoses. No adjustment for age, smoking or income. Fictional article and dataset."],
  "iq-18-015-article-analysis": ["Virtual reality and anatomy learning", "One medical school, four-week optional pilot. 32 of 160 students volunteered; 4 missed the final quiz. Mean score before 64%, after 72%; same 28 students and same 20 questions. 24/28 rated sessions useful. 6/32 reported dizziness. No comparison group; usual teaching continued. Setup £8,000. Lecturer taught and marked. No later or practical assessment. Fictional education pilot."],
  "iq-19-001-group-discussion": ["Healthcare improvement proposals", "Capacity for two programme launches next year. A Surgery: 1,400 waiting over a year; weekend operating lists; launch 3 months; staff cover unconfirmed. B Mental health: median wait 18 weeks; two community teams; launch 9 months; recruitment uncertain. C Maternity: gaps in overnight senior cover; extra cover and training; launch 6 months; harm rates not estimated. D Vaccination: uptake 84% locally and 72% in one area; outreach and translated invitations; launch 2 months; participation uncertain. E Buildings: 120 appointments cancelled last quarter; replace ventilation and electrics; completion 18 months; clinics must relocate. Fictional planning brief."],
  "iq-19-002-group-tasks": ["NHS improvement budget", "Total budget £10m, whole-project funding only. Community mental-health team £4m: earlier local support, specialist recruitment needed. Two operating theatres £6m: more surgical capacity, additional staff needed. Diabetes prevention £3m: reduce future illness, benefits take time. Digital-record upgrade £5m: information shared across services, training and transition needed. Rural mobile clinic £2m: reaches isolated communities, limited weekly visits. Fictional one-year project costs."],
  "iq-19-003-group-tasks": ["Overnight on the mountain", "Four adults, rain, 3°C overnight, dusk in 30 minutes. Carrying capacity five items. Available: waterproof sheet, first-aid kit, map, compass, dry matches, water (two litres total), rope (10 metres), torch, chocolate bars, phone (20% battery). Phone signal is intermittent. Fictional survival exercise."],
  "iq-19-008-group-tasks": ["Four patient presentations", "You are a student on placement; a clinician is nearby. A, age 67: new chest pressure and sweating, started 20 minutes ago. B, age 24: ankle pain after a fall, able to walk, injury one hour ago. C, age 45: prescription query, no current symptoms, routine medicine running low. D, age 5: fever, unusually difficult to wake, parent says this is not normal. Fictional cases."],
  "iq-20-001-prioritisation-stations": ["Assessment queue", "Five people need attention; clinical help is available. A: sudden facial droop and slurred speech, last well 15 minutes ago. B: mild rash for three weeks, no breathing difficulty. C: worsening breathlessness and blue lips, deteriorating over five minutes. D: routine medication refill, supply lasts three more days. E: deep cut, bleeding controlled by pressure. Fictional interview scenario."],
  "iq-20-002-prioritisation-stations": ["Five competing demands", "You are a student on placement. A: a fire alarm is sounding on your floor. B: a distressed friend has asked you to call. C: coursework is due in two hours. D: a patient's identification label may be wrong. E: you need food before the shop closes tonight. Fictional task sheet."],
  "iq-20-003-prioritisation-stations": ["Team inbox", "You are a student on placement. Requests arriving at 10:00. Nurse: a patient has become suddenly confused. Receptionist: a family wants an update. Pharmacist: a routine prescription needs clarification by the prescriber before 14:00. Student colleague: help requested with tomorrow's teaching. Manager: the monthly survey is due today. Fictional team messages."],
  "iq-20-004-prioritisation-stations": ["Health-service funding proposals", "£5m available for year one, whole-proposal funding only. Mental-health crisis line: £2m, estimated 4,000 users, repeat calls may affect capacity. New cancer scanner: £4m, 1,100 scans, staffing may delay full use. Community falls prevention: £1m, 3,000 older adults, attendance uncertain. Extra neonatal beds: £3m, 240 admissions, length of stay varies. These figures describe different activities, not equivalent health benefits. Fictional year-one estimates."],
  "iq-20-005-prioritisation-stations": ["Public-health investment estimates", "School vaccination outreach: year-one reach 1,200 children, cost £120,000, benefit horizon 3–12 months, parental consent uncertain. Smoking-cessation support: 800 adults, £80,000, 1–5 years, programme uptake uncertain. Air-quality monitoring: area covers 20,000 residents, £60,000, benefit depends on policy action, uncertainty about action on findings. Free community exercise: 1,500 adults, £45,000, 6–12 months, continued attendance uncertain. All costs are year one. Fictional estimates."],
  "iq-20-007-prioritisation-stations": ["A difficult Thursday", "Thursday: 09:00 compulsory seminar; 12:00 volunteering shift, cover may be available; 15:00 group-project meeting; 17:00 medical appointment booked two months ago; 18:00 family celebration. Friday 09:00 coursework due; three hours of coursework still to do. Fictional planning exercise."],
  "iq-20-008-prioritisation-stations": ["Four patient-safety concerns", "You are a student on placement; senior help available. A: medicine administered despite a documented allergy to it; patient currently feels well. B: vaccine fridge 1°C above its displayed permitted range, vaccines inside, duration unknown. C: medicine nearly given to the wrong patient, caught before administration. D: small corridor spill with missing wet-floor sign; corridor currently empty. Fictional incidents."],
  "iq-20-009-prioritisation-stations": ["Several events happen at once", "Hospital corridor; you are a student on placement. A: smoke visible at a closed store-room door. B: a visitor has collapsed nearby. C: another visitor is filming. D: a colleague asks you to fetch confidential notes. E: the fire alarm has not sounded. Fictional interview scenario."],
};

export const interviewStimuli: readonly InterviewStimulus[] = Object.entries(sources).map(([id, [title, description]]) => ({
  id, src: `/phloemai/interview-stimuli/${id}.png`, title, description,
}));
const stimuliById = new Map(interviewStimuli.map((stimulus) => [stimulus.id, stimulus]));

export function getQuestionStimulus(questionId: string | null | undefined) {
  return questionId ? stimuliById.get(questionId) ?? null : null;
}
